/* Generated by Together */

package it.finsiel.siged.mvc.presentation.helper;

public class AllaccioView {
    public AllaccioView() {
    }

    private int protAllacciatoId;

    private int numProtAllacciato;

    private int annoProtAllacciato;

    private String annoNumeroProtocollo;

    private String dataProtocollo;

    private String tipoProtocollo;

    private String mittente;

    private String Oggetto;

    private String checkAllacci;

    /**
     * @return Returns the annoProtAllacciato.
     */
    public int getAnnoProtAllacciato() {
        return annoProtAllacciato;
    }

    /**
     * @param annoProtAllacciato
     *            The annoProtAllacciato to set.
     */
    public void setAnnoProtAllacciato(int annoProtAllacciato) {
        this.annoProtAllacciato = annoProtAllacciato;
    }

    /**
     * @return Returns the numProtAllacciato.
     */
    public int getNumProtAllacciato() {
        return numProtAllacciato;
    }

    /**
     * @param numProtAllacciato
     *            The numProtAllacciato to set.
     */
    public void setNumProtAllacciato(int numProtAllacciato) {
        this.numProtAllacciato = numProtAllacciato;
    }

    /**
     * @return Returns the protAllacciatoId.
     */
    public int getProtAllacciatoId() {
        return protAllacciatoId;
    }

    /**
     * @param protAllacciatoId
     *            The protAllacciatoId to set.
     */
    public void setProtAllacciatoId(int protAllacciatoId) {
        this.protAllacciatoId = protAllacciatoId;
    }

    /**
     * @return Returns the dataProtocollo.
     */
    public String getDataProtocollo() {
        return dataProtocollo;
    }

    /**
     * @param dataProtocollo
     *            The dataProtocollo to set.
     */
    public void setDataProtocollo(String dataProtocollo) {
        this.dataProtocollo = dataProtocollo;
    }

    /**
     * @return Returns the mittente.
     */
    public String getMittente() {
        return mittente;
    }

    /**
     * @param mittente
     *            The mittente to set.
     */
    public void setMittente(String mittente) {
        this.mittente = mittente;
    }

    /**
     * @return Returns the ogetto.
     */
    public String getOggetto() {
        return Oggetto;
    }

    /**
     * @param ogetto
     *            The ogetto to set.
     */
    public void setOggetto(String ogetto) {
        Oggetto = ogetto;
    }

    /**
     * @return Returns the tipoProtocollo.
     */
    public String getTipoProtocollo() {
        return tipoProtocollo;
    }

    /**
     * @param tipoProtocollo
     *            The tipoProtocollo to set.
     */
    public void setTipoProtocollo(String tipoProtocollo) {
        this.tipoProtocollo = tipoProtocollo;
    }

    /**
     * @return Returns the checkAllacci.
     */
    public String getCheckAllacci() {
        return checkAllacci;
    }

    /**
     * @param checkAllacci
     *            The checkAllacci to set.
     */
    public void setCheckAllacci(String checkAllacci) {
        this.checkAllacci = checkAllacci;
    }

    /**
     * @return Returns the annoNumeroProtocollo.
     */
    public String getAnnoNumeroProtocollo() {
        return annoNumeroProtocollo;
    }

    /**
     * @param annoNumeroProtocollo
     *            The annoNumeroProtocollo to set.
     */
    public void setAnnoNumeroProtocollo(String annoNumeroProtocollo) {
        this.annoNumeroProtocollo = annoNumeroProtocollo;
    }
}