/* Generated by Together */

package it.finsiel.siged.mvc.presentation.helper;

import java.util.HashMap;
import java.util.Map;

public class DocumentoView {

    private int documentoId;

    private String filename; // Inserito il 16/02/06 per gestire il linkDoc

    private String dataDocumento;

    private String nome;

    private String tipoDocumento;

    private String argomento;

    private String oggetto;

    private String stato;

    private String statoLav;

    private String usernameLav;

    private int versione;

    private String dataModifica;

    // todo: filtro Ricerca archivio Documentale

    private String descrizione;

    private String note;

    private String tipoDocumentoId;
    
    private String owner;
    
    private String assegnatoDa;
    
    private String messaggio;

    private Map params = new HashMap(2);

    public DocumentoView() {
    }

    public Map getParams() {
        return params;
    }

    public void setParams(Map params) {
        this.params = params;
    }

    public int getVersione() {
        return versione;
    }

    public void setVersione(int versione) {
        this.versione = versione;
    }

    public String getArgomento() {
        return argomento;
    }

    public void setArgomento(String argomento) {
        this.argomento = argomento;
    }

    public String getDataDocumento() {
        return dataDocumento;
    }

    public void setDataDocumento(String dataDocumento) {
        this.dataDocumento = dataDocumento;
    }

    public int getDocumentoId() {
        return documentoId;
    }

    public void setDocumentoId(int documentoId) {
        this.documentoId = documentoId;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getOggetto() {
        return oggetto;
    }

    public void setOggetto(String oggetto) {
        this.oggetto = oggetto;
    }

    public String getTipoDocumento() {
        return tipoDocumento;
    }

    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    public String getStato() {
        return stato;
    }

    public void setStato(String stato) {
        this.stato = stato;
    }

    public String getDataModifica() {
        return dataModifica;
    }

    public void setDataModifica(String dataModifica) {
        this.dataModifica = dataModifica;
    }

    public String getStatoLav() {
        return statoLav;
    }

    public void setStatoLav(String statoLav) {
        this.statoLav = statoLav;
    }

    public String getUsernameLav() {
        return usernameLav;
    }

    public void setUsernameLav(String usernameLav) {
        this.usernameLav = usernameLav;
    }

    // todo: filtro Ricerca archivio Documentale

    public String getDescrizione() {
        return descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getTipoDocumentoId() {
        return tipoDocumentoId;
    }

    public void setTipoDocumentoId(String tipoDocumentoId) {
        this.tipoDocumentoId = tipoDocumentoId;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public String getAssegnatoDa() {
        return assegnatoDa;
    }

    public void setAssegnatoDa(String assegnatoDa) {
        this.assegnatoDa = assegnatoDa;
    }

    public String getMessaggio() {
        return messaggio;
    }

    public void setMessaggio(String messaggio) {
        this.messaggio = messaggio;
    }
}