/* Generated by Together */

package it.finsiel.siged.mvc.presentation.helper;

import it.finsiel.siged.mvc.vo.BaseVO;

/**
 * @persistent
 * @rdbPhysicalName MESSAGGI_INGRESSO
 * @rdbPhysicalPrimaryKeyName SYS_C0022142
 */
public class EmailView extends BaseVO {
    public EmailView() {
    }

    private String testoMessaggio;

    private String nomeMittente;

    private String emailMittente;

    private String dataSpedizione;

    private int numeroAllegati;

    public String getDataSpedizione() {
        return dataSpedizione;
    }

    public void setDataSpedizione(String dataSpedizione) {
        this.dataSpedizione = dataSpedizione;
    }

    public String getEmailMittente() {
        return emailMittente;
    }

    public void setEmailMittente(String emailMittente) {
        this.emailMittente = emailMittente;
    }

    public String getNomeMittente() {
        return nomeMittente;
    }

    public void setNomeMittente(String nomeMittente) {
        this.nomeMittente = nomeMittente;
    }

    public int getNumeroAllegati() {
        return numeroAllegati;
    }

    public void setNumeroAllegati(int numeroAllegati) {
        this.numeroAllegati = numeroAllegati;
    }

    public String getTestoMessaggio() {
        return testoMessaggio;
    }

    public void setTestoMessaggio(String testoMessaggio) {
        this.testoMessaggio = testoMessaggio;
    }
}