/* Generated by Together */

package it.finsiel.siged.mvc.presentation.helper;

import it.finsiel.siged.model.organizzazione.Organizzazione;
import it.finsiel.siged.model.organizzazione.Ufficio;
import it.finsiel.siged.mvc.bo.TitolarioBO;

import java.sql.Date;

public class FaldoneView {

    public FaldoneView() {
    }

    private int id;
    
    private int aooId;
    
    private String oggetto;
    
    private Date rowCreatedTime;
    
    private String rowCreatedUser;
    
    private Date rowUpdatedTime;
    
    private String rowUpdatedUser;
    
    private String sottoCategoria;
    
    private String nota;

    private String numeroFaldone;

    private int anno;
    
    private int numero;
    
    private String palazzo;
    
    private String piano;
    
    private String stanza;
    
    private String edificio;
    
    private String dataCreazione;
    
    private String dataCarico;
    
    private String dataScarico;
    
    private String dataEvidenza;
    
    private String dataMovimento;
    
    private int ufficioId;

    private String ufficio;

    private int titolarioId;

    private String codiceLocale;
    
    private int statoId;
    
    private int versione;
    
    private String posizioneSelezionata;
    
    private int posizioneSelezionataId;
    
    
    
    

    public String getPosizioneSelezionata() {
        return posizioneSelezionata;
    }

    public void setPosizioneSelezionata(String posizioneSelezionata) {
        this.posizioneSelezionata = posizioneSelezionata;
    }

    public int getPosizioneSelezionataId() {
        return posizioneSelezionataId;
    }

    public void setPosizioneSelezionataId(int posizioneSelezionataId) {
        this.posizioneSelezionataId = posizioneSelezionataId;
    }

    public int getAnno() {
        return anno;
    }

    public void setAnno(int anno) {
        this.anno = anno;
    }

    public int getAooId() {
        return aooId;
    }

    public void setAooId(int aooId) {
        this.aooId = aooId;
    }

    public String getDataCarico() {
        return dataCarico;
    }

    public void setDataCarico(String dataCarico) {
        this.dataCarico = dataCarico;
    }

    public String getDataEvidenza() {
        return dataEvidenza;
    }

    public void setDataEvidenza(String dataEvidenza) {
        this.dataEvidenza = dataEvidenza;
    }

    public String getDataMovimento() {
        return dataMovimento;
    }

    public void setDataMovimento(String dataMovimento) {
        this.dataMovimento = dataMovimento;
    }

    public String getDataScarico() {
        return dataScarico;
    }

    public void setDataScarico(String dataScarico) {
        this.dataScarico = dataScarico;
    }

    public String getEdificio() {
        return edificio;
    }

    public void setEdificio(String edificio) {
        this.edificio = edificio;
    }

    public String getNota() {
        return nota;
    }

    public void setNota(String nota) {
        this.nota = nota;
    }

    public int getNumero() {
        return numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    public String getPalazzo() {
        return palazzo;
    }

    public void setPalazzo(String palazzo) {
        this.palazzo = palazzo;
    }

    public String getPiano() {
        return piano;
    }

    public void setPiano(String piano) {
        this.piano = piano;
    }

    public Date getRowCreatedTime() {
        return rowCreatedTime;
    }

    public void setRowCreatedTime(Date rowCreatedTime) {
        this.rowCreatedTime = rowCreatedTime;
    }

    public String getRowCreatedUser() {
        return rowCreatedUser;
    }

    public void setRowCreatedUser(String rowCreatedUser) {
        this.rowCreatedUser = rowCreatedUser;
    }

    public Date getRowUpdatedTime() {
        return rowUpdatedTime;
    }

    public void setRowUpdatedTime(Date rowUpdatedTime) {
        this.rowUpdatedTime = rowUpdatedTime;
    }

    public String getRowUpdatedUser() {
        return rowUpdatedUser;
    }

    public void setRowUpdatedUser(String rowUpdatedUser) {
        this.rowUpdatedUser = rowUpdatedUser;
    }

    public String getSottoCategoria() {
        return sottoCategoria;
    }

    public void setSottoCategoria(String sottoCategoria) {
        this.sottoCategoria = sottoCategoria;
    }

    public String getStanza() {
        return stanza;
    }

    public void setStanza(String stanza) {
        this.stanza = stanza;
    }

    public int getStatoId() {
        return statoId;
    }

    public void setStatoId(int statoId) {
        this.statoId = statoId;
    }

    public int getVersione() {
        return versione;
    }

    public void setVersione(int versione) {
        this.versione = versione;
    }

    public String getDataCreazione() {
        return dataCreazione;
    }

    public void setDataCreazione(String dataApertura) {
        this.dataCreazione = dataApertura;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getOggetto() {
        return oggetto;
    }

    public void setOggetto(String oggetto) {
        this.oggetto = oggetto;
    }

    public String getNumeroFaldone() {
        return numeroFaldone;
    }

    public void setNumeroFaldone(String numeroFaldone) {
        this.numeroFaldone = numeroFaldone;
    }

    public int getTitolarioId() {
        return titolarioId;
    }

    public void setTitolarioId(int titolarioId) {
        this.titolarioId = titolarioId;
    }

    public String getUfficio() {
        return ufficio;
    }

    public void setUfficio(String ufficio) {
        this.ufficio = ufficio;
    }

    public int getUfficioId() {
        return ufficioId;
    }

    public void setUfficioId(int ufficioId) {
        this.ufficioId = ufficioId;
    }

    public String getPathTitolario() {
        return TitolarioBO.getPathDescrizioneTitolario(getTitolarioId());
    }

    public String getCodiceLocale() {
        return codiceLocale;
    }

    public void setCodiceLocale(String codiceLocale) {
        this.codiceLocale = codiceLocale;
    }

    public String getDescUfficio() {
        Ufficio u = Organizzazione.getInstance().getUfficio(getUfficioId());
        if (u != null && u.getValueObject() != null)
            return u.getValueObject().getDescription();
        else
            return "";
    }

}