/* Generated by Together */

package it.finsiel.siged.mvc.presentation.helper;

import it.finsiel.siged.model.organizzazione.Organizzazione;
import it.finsiel.siged.mvc.bo.TitolarioBO;
import it.finsiel.siged.mvc.business.LookupDelegate;
import it.finsiel.siged.util.DateUtil;
import it.finsiel.siged.util.StringUtil;

public class FascicoloView {

    public FascicoloView() {
    }

    private int id;

    private String nome;

    private String stato;

    private String oggetto;

    private String note;

    private String dataApertura;

    private int fascicoloId;

    private int ufficioIntestatarioId;

    private int utenteIntestatarioId;

    private int ufficioResponsabileId;

    private int utenteResponsabileId;

    private String dataEvidenza;

    private String descUfficioIntestatarioId;

    private int titolarioId;

    private int progressivo;

    private int annoRiferimento;

    private int versione;

    private String dataCarico;

    private String dataScarico;

    private String descrizioneUfficioIntestatario;

    public String getDescrizioneStato() {
        return (String) (LookupDelegate.getInstance().getStatiFascicolo())
                .get(new Integer(getStato()));
    }

    public String getDescrizioneUfficioIntestatario() {
        Organizzazione org = Organizzazione.getInstance();
        return org.getUfficio(getUfficioIntestatarioId()).getPath();
    }

    public String getDescrizioneUtenteIntestatario() {
        if (getUtenteIntestatarioId() > 0) {
            Organizzazione org = Organizzazione.getInstance();
            return org.getUtente(getUtenteIntestatarioId()).getValueObject()
                    .getFullName();
        } else {
            return "";
        }

    }

    public String getDescUfficioIntestatarioId() {
        return descUfficioIntestatarioId;
    }

    public void setDescUfficioIntestatarioId(String descUfficioIntestatarioId) {
        this.descUfficioIntestatarioId = descUfficioIntestatarioId;
    }

    public String getPathTitolario() {
        return TitolarioBO.getPathDescrizioneTitolario(getTitolarioId());
    }

    public String getStato() {
        return stato;
    }

    public void setStato(String stato) {
        this.stato = stato;
    }

    public String getDataApertura() {
        return dataApertura;
    }

    public void setDataApertura(String dataApertura) {
        this.dataApertura = dataApertura;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getOggetto() {
        return oggetto;
    }

    public void setOggetto(String oggetto) {
        this.oggetto = oggetto;
    }

    public String getDataEvidenza() {
        return dataEvidenza;
    }

    public void setDataEvidenza(String dataEvidenza) {
        this.dataEvidenza = dataEvidenza;
    }

    public int getFascicoloId() {
        return fascicoloId;
    }

    public void setFascicoloId(int fascicoloId) {
        this.fascicoloId = fascicoloId;
    }

    public int getUfficioIntestatarioId() {
        return ufficioIntestatarioId;
    }

    public void setUfficioIntestatarioId(int ufficioIntestatarioId) {
        this.ufficioIntestatarioId = ufficioIntestatarioId;
    }

    public int getTitolarioId() {
        return titolarioId;
    }

    public void setTitolarioId(int titolarioId) {
        this.titolarioId = titolarioId;
    }

    public int getAnnoRiferimento() {
        return annoRiferimento;
    }

    public void setAnnoRiferimento(int annoRiferimento) {
        this.annoRiferimento = annoRiferimento;
    }

    public int getProgressivo() {
        return progressivo;
    }

    public void setProgressivo(int progressivo) {
        this.progressivo = progressivo;
    }

    public String getAnnoProgressivo() {
        // if (getAnnoRiferimento() > 0 && getProgressivo() > 0) {
        if (getDataApertura() != null && getProgressivo() > 0) {

            return DateUtil.getYear(DateUtil.toDate(dataApertura))
                    + StringUtil.formattaNumeroProtocollo(String
                            .valueOf(progressivo), 6);
        }
        return null;
    }

    public int getVersione() {
        return versione;
    }

    public void setVersione(int versione) {
        this.versione = versione;
    }

    public String getDataCarico() {
        return dataCarico;
    }

    public void setDataCarico(String dataCarico) {
        this.dataCarico = dataCarico;
    }

    public String getDataScarico() {
        return dataScarico;
    }

    public void setDataScarico(String dataScarico) {
        this.dataScarico = dataScarico;
    }

    public int getUtenteIntestatarioId() {
        return utenteIntestatarioId;
    }

    public void setUtenteIntestatarioId(int utenteIntestatarioId) {
        this.utenteIntestatarioId = utenteIntestatarioId;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public void setUfficioResponsabileId(int ufficioResponsabileId) {
        this.ufficioResponsabileId = ufficioResponsabileId;
    }

    public void setUtenteResponsabileId(int utenteResponsabileId) {
        this.utenteResponsabileId = utenteResponsabileId;
    }

    public int getUfficioResponsabileId() {
        return ufficioResponsabileId;
    }

    public int getUtenteResponsabileId() {
        return utenteResponsabileId;
    }

    public String getDescrizioneUfficioResponsabile() {
        Organizzazione org = Organizzazione.getInstance();
        return org.getUfficio(getUfficioResponsabileId()).getPath();
    }

    public String getDescrizioneUtenteResponsabile() {
        if (getUtenteResponsabileId() > 0) {
            Organizzazione org = Organizzazione.getInstance();
            return org.getUtente(getUtenteResponsabileId()).getValueObject()
                    .getFullName();
        } else {
            return "";
        }

    }

}