/* Generated by Together */

package it.finsiel.siged.mvc.presentation.helper;

/**
 * @persistent
 * @rdbPhysicalName PROTOCOLLO_ALLACCI
 * @rdbPhysicalPrimaryKeyName SYS_C0022186
 */
public class MittenteView {
    public MittenteView() {
    }

    public MittenteView(String nome, String cognome, String denominazione,
            String tipo) {
        this.cognome = cognome;
        this.nome = nome;
        this.denominazione = denominazione;
        this.tipo = tipo;
    }

    private String nome;

    private String cognome;

    private String denominazione;

    private String tipo;// persona fisica F, persona giuridica G

    /**
     * @return Returns the cognome.
     */
    public String getCognome() {
        return cognome;
    }

    /**
     * @param cognome
     *            The cognome to set.
     */
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    /**
     * @return Returns the denominazione.
     */
    public String getDenominazione() {
        return denominazione;
    }

    /**
     * @param denominazione
     *            The denominazione to set.
     */
    public void setDenominazione(String denominazione) {
        this.denominazione = denominazione;
    }

    /**
     * @return Returns the nome.
     */
    public String getNome() {
        return nome;
    }

    /**
     * @param nome
     *            The nome to set.
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * @return Returns the tipo.
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * @param tipo
     *            The tipo to set.
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getMittente() {
        if (denominazione != null && !"".equals(denominazione.trim())) {
            return denominazione;
        } else
            return cognome + " " + nome;
    }
}