/* Generated by Together */

package it.finsiel.siged.mvc.presentation.helper;

public class ProtocolloFascicoloView {
    public ProtocolloFascicoloView() {
    }

    private int id;

    private int protocolloId;

    private String dataDocumento;

    private String tipo; // P=protocollo;D=documento

    private String nome;

    private String tipoDocumento;

    private String dataProtocollo;

    private int numeroProtocollo;

    private String tipoProtocollo;

    private String argomento;

    private String oggetto;
    
    private boolean riservato;

    public String getArgomento() {
        return argomento;
    }

    public void setArgomento(String argomento) {
        this.argomento = argomento;
    }

    public String getTipoDocumento() {
        return tipoDocumento;
    }

    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    public String getDataDocumento() {
        return dataDocumento;
    }

    public void setDataDocumento(String data) {
        this.dataDocumento = data;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getOggetto() {
        return oggetto;
    }

    public void setOggetto(String oggetto) {
        this.oggetto = oggetto;
    }

    public String getDataProtocollo() {
        return dataProtocollo;
    }

    public void setDataProtocollo(String dataProtocollo) {
        this.dataProtocollo = dataProtocollo;
    }

    public int getNumeroProtocollo() {
        return numeroProtocollo;
    }

    public void setNumeroProtocollo(int numeroProtocollo) {
        this.numeroProtocollo = numeroProtocollo;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getTipoProtocollo() {
        return tipoProtocollo;
    }

    public void setTipoProtocollo(String tipoProtocollo) {
        this.tipoProtocollo = tipoProtocollo;
    }

    public int getProtocolloId() {
        return protocolloId;
    }

    public void setProtocolloId(int protocolloId) {
        this.protocolloId = protocolloId;
    }

    public boolean isRiservato() {
        return riservato;
    }

    public void setRiservato(boolean riservato) {
        this.riservato = riservato;
    }
    
}