/* Generated by Together */

package it.finsiel.siged.mvc.presentation.helper;

public class ProtocolloView {

    public ProtocolloView() {
    }

    private int id;

    private String oggetto;

    private String numeroProtocollo;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getOggetto() {
        return oggetto;
    }

    public void setOggetto(String oggetto) {
        this.oggetto = oggetto;
    }

    public String getNumeroProtocollo() {
        return numeroProtocollo;
    }

    public void setNumeroProtocollo(String n) {
        this.numeroProtocollo = n;
    }
}