/* Generated by Together */

package it.finsiel.siged.mvc.presentation.helper;

public class UtenteView {
    public UtenteView() {
    }

    private int id;

    private String cognome;

    private String nome;

    private boolean referente;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCognome() {
        return cognome;
    }

    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public boolean getReferente() {
        return referente;
    }

    public void setReferente(boolean referente) {
        this.referente = referente;
    }

}