/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

import it.finsiel.siged.mvc.vo.VersioneVO;

/**
 * @persistent
 * @rdbPhysicalName TIPI_DOCUMENTO
 * @rdbPhysicalPrimaryKeyName SYS_C0022087
 */
public class DestinatarioAllaccioVO extends VersioneVO {

    public DestinatarioAllaccioVO() {
    }

    private String allaccio;

    private String destinatario;

    public String getAllaccio() {
        return allaccio;
    }

    public void setAllaccio(String allaccio) {
        this.allaccio = allaccio;
    }

    public String getDestinatario() {
        return destinatario;
    }

    public void setDestinatario(String destinatario) {
        this.destinatario = destinatario;
    }
}