/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

import it.finsiel.siged.mvc.vo.VersioneVO;
import it.finsiel.siged.mvc.vo.protocollo.ProtocolloVO;

/**
 * @persistent
 * @rdbPhysicalName DETTAGLIO_TIPO_DOC
 * @rdbPhysicalPrimaryKeyName SYS_C0022265
 */
public class DettaglioTipoDoc extends VersioneVO {
    public DettaglioTipoDoc() {
    }

    /**
     * @rdbPhysicalName DETTAGLIO_TIPO_DOC_ID
     * @rdbNotNull
     * @rdbSize 22
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL
     * @rdbPrimaryKey
     */
    private long dettaglioTipoDocId;

    /**
     * @rdbPhysicalName TEXT_VALORE
     * @rdbSize 100
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String textValore;

    private ProtocolloVO fkProtocollo;

    /**
     * @rdbPhysicalName SYS_C0022266
     * @rdbOptional
     */
    private StrutturaTipoDocVO fkStrutturaTipoDoc;

    /**
     * @return Returns the dettaglioTipoDocId.
     */
    public long getDettaglioTipoDocId() {
        return dettaglioTipoDocId;
    }

    /**
     * @param dettaglioTipoDocId
     *            The dettaglioTipoDocId to set.
     */
    public void setDettaglioTipoDocId(long dettaglioTipoDocId) {
        this.dettaglioTipoDocId = dettaglioTipoDocId;
    }

    /**
     * @return Returns the fkProtocollo.
     */
    public ProtocolloVO getFkProtocollo() {
        return fkProtocollo;
    }

    /**
     * @param fkProtocollo
     *            The fkProtocollo to set.
     */
    public void setFkProtocollo(ProtocolloVO fkProtocollo) {
        this.fkProtocollo = fkProtocollo;
    }

    /**
     * @return Returns the fkStrutturaTipoDoc.
     */
    public StrutturaTipoDocVO getFkStrutturaTipoDoc() {
        return fkStrutturaTipoDoc;
    }

    /**
     * @param fkStrutturaTipoDoc
     *            The fkStrutturaTipoDoc to set.
     */
    public void setFkStrutturaTipoDoc(StrutturaTipoDocVO fkStrutturaTipoDoc) {
        this.fkStrutturaTipoDoc = fkStrutturaTipoDoc;
    }

    /**
     * @return Returns the textValore.
     */
    public String getTextValore() {
        return textValore;
    }

    /**
     * @param textValore
     *            The textValore to set.
     */
    public void setTextValore(String textValore) {
        this.textValore = textValore;
    }
}