/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

import it.finsiel.siged.mvc.vo.organizzazione.UfficioVO;
import it.finsiel.siged.mvc.vo.registro.RegistroVO;

import java.util.Date;

/**
 * @persistent
 * @rdbPhysicalName ELENCHI
 * @rdbPhysicalPrimaryKeyName SYS_C0022194
 */
public class ElencoVO {
    public ElencoVO() {
    }

    /**
     * @rdbPhysicalName ELENCHI_ID
     * @rdbNotNull
     * @rdbSize 22
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL
     * @rdbPrimaryKey
     */
    private long elencoId;

    /**
     * @rdbPhysicalName NUME_ELENCO
     * @rdbNotNull
     * @rdbSize 22
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL
     */
    private long numElenco;

    /**
     * @rdbPhysicalName ANNO_ELENCO
     * @rdbNotNull
     * @rdbSize 22
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL
     */
    private long annoElenco;

    /**
     * @rdbPhysicalName DATA_APERTURA_ELENCO
     * @rdbNotNull
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType TIMESTAMP
     */
    private Date dataAperturaElenco;

    /**
     * @rdbPhysicalName DATA_CHIUSURA_ELENCO
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType TIMESTAMP
     */
    private Date dataChiusuraElenco;

    /** @rdbPhysicalName SYS_C0022197 */
    private RegistroVO fkRegistro;

    /**
     * @rdbPhysicalName SYS_C0022196
     * @rdbOptional
     */
    private UfficioVO fkUfficioAssegnatario;

    /**
     * @rdbPhysicalName SYS_C0022195
     * @rdbOptional
     */
    private UfficioVO fkUfficioAssegnante;

    /**
     * @return Returns the annoElenco.
     */
    public long getAnnoElenco() {
        return annoElenco;
    }

    /**
     * @param annoElenco
     *            The annoElenco to set.
     */
    public void setAnnoElenco(long annoElenco) {
        this.annoElenco = annoElenco;
    }

    /**
     * @return Returns the dataAperturaElenco.
     */
    public Date getDataAperturaElenco() {
        return dataAperturaElenco;
    }

    /**
     * @param dataAperturaElenco
     *            The dataAperturaElenco to set.
     */
    public void setDataAperturaElenco(Date dataAperturaElenco) {
        this.dataAperturaElenco = dataAperturaElenco;
    }

    /**
     * @return Returns the dataChiusuraElenco.
     */
    public Date getDataChiusuraElenco() {
        return dataChiusuraElenco;
    }

    /**
     * @param dataChiusuraElenco
     *            The dataChiusuraElenco to set.
     */
    public void setDataChiusuraElenco(Date dataChiusuraElenco) {
        this.dataChiusuraElenco = dataChiusuraElenco;
    }

    /**
     * @return Returns the elencoId.
     */
    public long getElencoId() {
        return elencoId;
    }

    /**
     * @param elencoId
     *            The elencoId to set.
     */
    public void setElencoId(long elencoId) {
        this.elencoId = elencoId;
    }

    /**
     * @return Returns the fkRegistro.
     */
    public RegistroVO getFkRegistro() {
        return fkRegistro;
    }

    /**
     * @param fkRegistro
     *            The fkRegistro to set.
     */
    public void setFkRegistro(RegistroVO fkRegistro) {
        this.fkRegistro = fkRegistro;
    }

    /**
     * @return Returns the fkUfficioAssegnante.
     */
    public UfficioVO getFkUfficioAssegnante() {
        return fkUfficioAssegnante;
    }

    /**
     * @param fkUfficioAssegnante
     *            The fkUfficioAssegnante to set.
     */
    public void setFkUfficioAssegnante(UfficioVO fkUfficioAssegnante) {
        this.fkUfficioAssegnante = fkUfficioAssegnante;
    }

    /**
     * @return Returns the fkUfficioAssegnatario.
     */
    public UfficioVO getFkUfficioAssegnatario() {
        return fkUfficioAssegnatario;
    }

    /**
     * @param fkUfficioAssegnatario
     *            The fkUfficioAssegnatario to set.
     */
    public void setFkUfficioAssegnatario(UfficioVO fkUfficioAssegnatario) {
        this.fkUfficioAssegnatario = fkUfficioAssegnatario;
    }

    /**
     * @return Returns the numElenco.
     */
    public long getNumElenco() {
        return numElenco;
    }

    /**
     * @param numElenco
     *            The numElenco to set.
     */
    public void setNumElenco(long numElenco) {
        this.numElenco = numElenco;
    }
}