/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

/**
 * @persistent
 * @rdbPhysicalName MESSAGGI
 * @rdbPhysicalPrimaryKeyName SYS_C0022013
 */
public class MessaggioVO {
    public MessaggioVO() {
    }

    /**
     * @return Returns the descrizioneMessaggio.
     */
    public String getDescrizioneMessaggio() {
        return descrizioneMessaggio;
    }

    /**
     * @param descrizioneMessaggio
     *            The descrizioneMessaggio to set.
     */
    public void setDescrizioneMessaggio(String descrizioneMessaggio) {
        this.descrizioneMessaggio = descrizioneMessaggio;
    }

    /**
     * @return Returns the messaggioId.
     */
    public String getMessaggioId() {
        return messaggioId;
    }

    /**
     * @param messaggioId
     *            The messaggioId to set.
     */
    public void setMessaggioId(String messaggioId) {
        this.messaggioId = messaggioId;
    }

    /**
     * @return Returns the statoTipoMessaggio.
     */
    public String getStatoTipoMessaggio() {
        return statoTipoMessaggio;
    }

    /**
     * @param statoTipoMessaggio
     *            The statoTipoMessaggio to set.
     */
    public void setStatoTipoMessaggio(String statoTipoMessaggio) {
        this.statoTipoMessaggio = statoTipoMessaggio;
    }

    /**
     * @rdbPhysicalName MESSAGGI_ID
     * @rdbNotNull
     * @rdbSize 12
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     * @rdbPrimaryKey
     */
    private String messaggioId;

    /**
     * @rdbPhysicalName DESC_MESSAGGIO
     * @rdbNotNull
     * @rdbSize 100
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String descrizioneMessaggio;

    /**
     * @rdbPhysicalName STAT_TIPOMESSAGGIO
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR
     */
    private String statoTipoMessaggio;

}