/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

import it.finsiel.siged.mvc.vo.VersioneVO;

import java.util.Date;

/**
 * @persistent
 * @rdbPhysicalName PROFILI
 * @rdbPhysicalPrimaryKeyName SYS_C0022018
 */
public class ProfiloVO extends VersioneVO {
    public ProfiloVO() {
    }

    private int aooId;

    private String codProfilo;

    private String descrizioneProfilo;

    private Date dataInizioValidita;

    private Date dataFineValidita;

    private String[] menuProfilo;

    /**
     * @return Returns the codProfilo.
     */
    public String getCodProfilo() {
        return codProfilo;
    }

    /**
     * @param codProfilo
     *            The codProfilo to set.
     */
    public void setCodProfilo(String codProfilo) {
        this.codProfilo = codProfilo;
    }

    /**
     * @return Returns the dataFineValidita.
     */
    public Date getDataFineValidita() {
        return dataFineValidita;
    }

    /**
     * @param dataFineValidita
     *            The dataFineValidita to set.
     */
    public void setDataFineValidita(Date dataFineValidita) {
        this.dataFineValidita = dataFineValidita;
    }

    /**
     * @return Returns the dataInizioValidita.
     */
    public Date getDataInizioValidita() {
        return dataInizioValidita;
    }

    /**
     * @param dataInizioValidita
     *            The dataInizioValidita to set.
     */
    public void setDataInizioValidita(Date dataInizioValidita) {
        this.dataInizioValidita = dataInizioValidita;
    }

    /**
     * @return Returns the descrizioneProfilo.
     */
    public String getDescrizioneProfilo() {
        return descrizioneProfilo;
    }

    /**
     * @param descrizioneProfilo
     *            The descrizioneProfilo to set.
     */
    public void setDescrizioneProfilo(String descrizioneProfilo) {
        this.descrizioneProfilo = descrizioneProfilo;
    }

    /**
     * @return Returns the menuProfili.
     */
    public String[] getMenuProfili() {
        return menuProfilo;
    }

    /**
     * @param menuProfili
     *            The menuProfili to set.
     */
    public void setMenuProfili(String[] menuProfilo) {
        this.menuProfilo = menuProfilo;
    }

    public int getAooId() {
        return aooId;
    }

    public void setAooId(int aooId) {
        this.aooId = aooId;
    }
}