/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

/**
 * @persistent
 * @rdbPhysicalName PROVINCE
 * @rdbPhysicalPrimaryKeyName SYS_C0021966
 */
public class ProvinciaVO {
    public ProvinciaVO() {
    }

    public ProvinciaVO(long provinciaId, String descrizioneProvincia) {
        this.provinciaId = provinciaId;
        this.descrizioneProvincia = descrizioneProvincia;
    }

    /**
     * @rdbPhysicalName provincia_id
     * @rdbNotNull
     * @rdbSize 22
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL
     * @rdbPrimaryKey
     */
    private long provinciaId;

    /**
     * @rdbPhysicalName CODI_PROVINCIA
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String codProvincia;

    /**
     * @rdbPhysicalName DESC_PROVINCIA
     * @rdbNotNull
     * @rdbSize 50
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String descrizioneProvincia;

    /** @rdbPhysicalName SYS_C0021967 */
    private RegioneVO fkRegione;

    /**
     * @return Returns the codProvincia.
     */
    public String getCodProvincia() {
        return codProvincia;
    }

    /**
     * @param codProvincia
     *            The codProvincia to set.
     */
    public void setCodProvincia(String codProvincia) {
        this.codProvincia = codProvincia;
    }

    /**
     * @return Returns the descrizioneProvincia.
     */
    public String getDescrizioneProvincia() {
        return descrizioneProvincia;
    }

    /**
     * @param descrizioneProvincia
     *            The descrizioneProvincia to set.
     */
    public void setDescrizioneProvincia(String descrizioneProvincia) {
        this.descrizioneProvincia = descrizioneProvincia;
    }

    /**
     * @return Returns the fkRegione.
     */
    public RegioneVO getFkRegione() {
        return fkRegione;
    }

    /**
     * @param fkRegione
     *            The fkRegione to set.
     */
    public void setFkRegione(RegioneVO fkRegione) {
        this.fkRegione = fkRegione;
    }

    /**
     * @return Returns the provinciaId.
     */
    public long getProvinciaId() {
        return provinciaId;
    }

    /**
     * @param provinciaId
     *            The provinciaId to set.
     */
    public void setProvinciaId(long provinciaId) {
        this.provinciaId = provinciaId;
    }
}