/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

/**
 * @persistent
 * @rdbPhysicalName REGIONI
 * @rdbPhysicalPrimaryKeyName SYS_C0021961
 */
public class RegioneVO {
    public RegioneVO() {
    }

    /**
     * @return Returns the descrizioneRegione.
     */
    public String getDescrizioneRegione() {
        return descrizioneRegione;
    }

    /**
     * @param descrizioneRegione
     *            The descrizioneRegione to set.
     */
    public void setDescrizioneRegione(String descrizioneRegione) {
        this.descrizioneRegione = descrizioneRegione;
    }

    /**
     * @return Returns the regioneId.
     */
    public long getRegioneId() {
        return regioneId;
    }

    /**
     * @param regioneId
     *            The regioneId to set.
     */
    public void setRegioneId(long regioneId) {
        this.regioneId = regioneId;
    }

    /**
     * @rdbPhysicalName REGIONE_ID
     * @rdbNotNull
     * @rdbSize 22
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL
     * @rdbPrimaryKey
     */
    private long regioneId;

    /**
     * @rdbPhysicalName DESC_REGIONE
     * @rdbNotNull
     * @rdbSize 50
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String descrizioneRegione;

}