/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

import it.finsiel.siged.mvc.vo.organizzazione.AreaOrganizzativaVO;

import java.util.Date;

/**
 * @persistent
 * @rdbPhysicalName RUBRICA
 * @rdbPhysicalPrimaryKeyName SYS_C0022071
 */
public class RubricaVO {
    public RubricaVO() {
    }

    /**
     * @rdbPhysicalName RUBRICA_ID
     * @rdbNotNull
     * @rdbSize 22
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL
     * @rdbPrimaryKey
     */
    private long rubricaId;

    /**
     * @rdbPhysicalName PERS_COGNOME
     * @rdbSize 100
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String cognome;

    /**
     * @rdbPhysicalName DESC_DITTA
     * @rdbSize 100
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String ragioneSociale;

    /**
     * @rdbPhysicalName PERS_NOME
     * @rdbSize 40
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String nome;

    /**
     * @rdbPhysicalName TEXT_NOTE
     * @rdbSize 500
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String textNote;

    /**
     * @rdbPhysicalName TELE_TELEFONO
     * @rdbSize 16
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String telefono;

    /**
     * @rdbPhysicalName TELE_FAX
     * @rdbSize 16
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String teleFax;

    /**
     * @rdbPhysicalName INDI_WEB
     * @rdbSize 50
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String indirizzoWeb;

    /**
     * @rdbPhysicalName INDI_EMAIL
     * @rdbSize 50
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String indirizzoEMail;

    /**
     * @rdbPhysicalName INDI_CAP
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String cap;

    /**
     * @rdbPhysicalName INDI_COMUNE
     * @rdbSize 50
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String indirizzoComune;

    /**
     * @rdbPhysicalName FLAG_IS_FOLDER
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR
     */
    private String flagIsFolder;

    /**
     * @rdbPhysicalName CODI_CODICE
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String codMatricola;

    /**
     * Solo per persone giuridiche 1 Pubblico 2 Privato
     * 
     * @rdbPhysicalName FLAG_SETTORE
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL
     */
    private long flagSettoreAppartenenza;

    /**
     * @rdbPhysicalName DESC_QUALIFICA
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String descrizioneQualifica;

    /**
     * @rdbPhysicalName INDI_DUG
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String indiDug;

    /**
     * @rdbPhysicalName INDI_TOPONIMO
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String indiToponimo;

    /**
     * @rdbPhysicalName INDI_CIVICO
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String indiCivico;

    /**
     * @rdbPhysicalName DATA_NASCITA
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType TIMESTAMP
     */
    private Date dataNascita;

    /**
     * @rdbPhysicalName SESSO
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String sesso;

    /**
     * @rdbPhysicalName CODI_PARTITA_IVA
     * @rdbSize 11
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String partitaIva;

    /**
     * @rdbPhysicalName DESC_COMUNE_NASCITA
     * @rdbSize 50
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String descrizioneComuneNascita;

    /**
     * @rdbPhysicalName PERS_REFERENTE
     * @rdbSize 90
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String referente;

    /**
     * @rdbPhysicalName TELE_REFERENTE
     * @rdbSize 16
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String telefonoReferente;

    /**
     * @rdbPhysicalName CODI_FISCALE
     * @rdbSize 16
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String codiceFiscale;

    /**
     * @rdbPhysicalName CODI_STATO_CIVILE
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String codiceStatoCivile;

    /**
     * @rdbPhysicalName FLAG_TIPO_RUBRICA
     * @rdbNotNull
     * @rdbSize 20
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String flagTipoRubrica;

    /** @rdbPhysicalName SYS_C0022072 */
    private AreaOrganizzativaVO fkAoo;

    /**
     * @rdbPhysicalName SYS_C0022073
     * @rdbOptional
     */
    private ProvinciaVO fkProvinciaNascita;

    /**
     * @rdbPhysicalName SYS_C0022074
     * @rdbOptional
     */
    private ProvinciaVO fkProvincia;

    /**
     * @return Returns the cap.
     */
    public String getCap() {
        return cap;
    }

    /**
     * @param cap
     *            The cap to set.
     */
    public void setCap(String cap) {
        this.cap = cap;
    }

    /**
     * @return Returns the codiceFiscale.
     */
    public String getCodiceFiscale() {
        return codiceFiscale;
    }

    /**
     * @param codiceFiscale
     *            The codiceFiscale to set.
     */
    public void setCodiceFiscale(String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
    }

    /**
     * @return Returns the codiceStatoCivile.
     */
    public String getCodiceStatoCivile() {
        return codiceStatoCivile;
    }

    /**
     * @param codiceStatoCivile
     *            The codiceStatoCivile to set.
     */
    public void setCodiceStatoCivile(String codiceStatoCivile) {
        this.codiceStatoCivile = codiceStatoCivile;
    }

    /**
     * @return Returns the codMatricola.
     */
    public String getCodMatricola() {
        return codMatricola;
    }

    /**
     * @param codMatricola
     *            The codMatricola to set.
     */
    public void setCodMatricola(String codMatricola) {
        this.codMatricola = codMatricola;
    }

    /**
     * @return Returns the cognome.
     */
    public String getCognome() {
        return cognome;
    }

    /**
     * @param cognome
     *            The cognome to set.
     */
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    /**
     * @return Returns the dataNascita.
     */
    public Date getDataNascita() {
        return dataNascita;
    }

    /**
     * @param dataNascita
     *            The dataNascita to set.
     */
    public void setDataNascita(Date dataNascita) {
        this.dataNascita = dataNascita;
    }

    /**
     * @return Returns the descrizioneComuneNascita.
     */
    public String getDescrizioneComuneNascita() {
        return descrizioneComuneNascita;
    }

    /**
     * @param descrizioneComuneNascita
     *            The descrizioneComuneNascita to set.
     */
    public void setDescrizioneComuneNascita(String descrizioneComuneNascita) {
        this.descrizioneComuneNascita = descrizioneComuneNascita;
    }

    /**
     * @return Returns the descrizioneQualifica.
     */
    public String getDescrizioneQualifica() {
        return descrizioneQualifica;
    }

    /**
     * @param descrizioneQualifica
     *            The descrizioneQualifica to set.
     */
    public void setDescrizioneQualifica(String descrizioneQualifica) {
        this.descrizioneQualifica = descrizioneQualifica;
    }

    /**
     * @return Returns the fkAoo.
     */
    public AreaOrganizzativaVO getFkAoo() {
        return fkAoo;
    }

    /**
     * @param fkAoo
     *            The fkAoo to set.
     */
    public void setFkAoo(AreaOrganizzativaVO fkAoo) {
        this.fkAoo = fkAoo;
    }

    /**
     * @return Returns the fkProvincia.
     */
    public ProvinciaVO getFkProvincia() {
        return fkProvincia;
    }

    /**
     * @param fkProvincia
     *            The fkProvincia to set.
     */
    public void setFkProvincia(ProvinciaVO fkProvincia) {
        this.fkProvincia = fkProvincia;
    }

    /**
     * @return Returns the fkProvinciaNascita.
     */
    public ProvinciaVO getFkProvinciaNascita() {
        return fkProvinciaNascita;
    }

    /**
     * @param fkProvinciaNascita
     *            The fkProvinciaNascita to set.
     */
    public void setFkProvinciaNascita(ProvinciaVO fkProvinciaNascita) {
        this.fkProvinciaNascita = fkProvinciaNascita;
    }

    /**
     * @return Returns the flagIsFolder.
     */
    public String getFlagIsFolder() {
        return flagIsFolder;
    }

    /**
     * @param flagIsFolder
     *            The flagIsFolder to set.
     */
    public void setFlagIsFolder(String flagIsFolder) {
        this.flagIsFolder = flagIsFolder;
    }

    /**
     * @return Returns the flagSettoreAppartenenza.
     */
    public long getFlagSettoreAppartenenza() {
        return flagSettoreAppartenenza;
    }

    /**
     * @param flagSettoreAppartenenza
     *            The flagSettoreAppartenenza to set.
     */
    public void setFlagSettoreAppartenenza(long flagSettoreAppartenenza) {
        this.flagSettoreAppartenenza = flagSettoreAppartenenza;
    }

    /**
     * @return Returns the flagTipoRubrica.
     */
    public String getFlagTipoRubrica() {
        return flagTipoRubrica;
    }

    /**
     * @param flagTipoRubrica
     *            The flagTipoRubrica to set.
     */
    public void setFlagTipoRubrica(String flagTipoRubrica) {
        this.flagTipoRubrica = flagTipoRubrica;
    }

    /**
     * @return Returns the indiCivico.
     */
    public String getIndiCivico() {
        return indiCivico;
    }

    /**
     * @param indiCivico
     *            The indiCivico to set.
     */
    public void setIndiCivico(String indiCivico) {
        this.indiCivico = indiCivico;
    }

    /**
     * @return Returns the indiDug.
     */
    public String getIndiDug() {
        return indiDug;
    }

    /**
     * @param indiDug
     *            The indiDug to set.
     */
    public void setIndiDug(String indiDug) {
        this.indiDug = indiDug;
    }

    /**
     * @return Returns the indirizzoComune.
     */
    public String getIndirizzoComune() {
        return indirizzoComune;
    }

    /**
     * @param indirizzoComune
     *            The indirizzoComune to set.
     */
    public void setIndirizzoComune(String indirizzoComune) {
        this.indirizzoComune = indirizzoComune;
    }

    /**
     * @return Returns the indirizzoEMail.
     */
    public String getIndirizzoEMail() {
        return indirizzoEMail;
    }

    /**
     * @param indirizzoEMail
     *            The indirizzoEMail to set.
     */
    public void setIndirizzoEMail(String indirizzoEMail) {
        this.indirizzoEMail = indirizzoEMail;
    }

    /**
     * @return Returns the indirizzoWeb.
     */
    public String getIndirizzoWeb() {
        return indirizzoWeb;
    }

    /**
     * @param indirizzoWeb
     *            The indirizzoWeb to set.
     */
    public void setIndirizzoWeb(String indirizzoWeb) {
        this.indirizzoWeb = indirizzoWeb;
    }

    /**
     * @return Returns the indiToponimo.
     */
    public String getIndiToponimo() {
        return indiToponimo;
    }

    /**
     * @param indiToponimo
     *            The indiToponimo to set.
     */
    public void setIndiToponimo(String indiToponimo) {
        this.indiToponimo = indiToponimo;
    }

    /**
     * @return Returns the nome.
     */
    public String getNome() {
        return nome;
    }

    /**
     * @param nome
     *            The nome to set.
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * @return Returns the partitaIva.
     */
    public String getPartitaIva() {
        return partitaIva;
    }

    /**
     * @param partitaIva
     *            The partitaIva to set.
     */
    public void setPartitaIva(String partitaIva) {
        this.partitaIva = partitaIva;
    }

    /**
     * @return Returns the ragioneSociale.
     */
    public String getRagioneSociale() {
        return ragioneSociale;
    }

    /**
     * @param ragioneSociale
     *            The ragioneSociale to set.
     */
    public void setRagioneSociale(String ragioneSociale) {
        this.ragioneSociale = ragioneSociale;
    }

    /**
     * @return Returns the referente.
     */
    public String getReferente() {
        return referente;
    }

    /**
     * @param referente
     *            The referente to set.
     */
    public void setReferente(String referente) {
        this.referente = referente;
    }

    /**
     * @return Returns the rubricaId.
     */
    public long getRubricaId() {
        return rubricaId;
    }

    /**
     * @param rubricaId
     *            The rubricaId to set.
     */
    public void setRubricaId(long rubricaId) {
        this.rubricaId = rubricaId;
    }

    /**
     * @return Returns the sesso.
     */
    public String getSesso() {
        return sesso;
    }

    /**
     * @param sesso
     *            The sesso to set.
     */
    public void setSesso(String sesso) {
        this.sesso = sesso;
    }

    /**
     * @return Returns the teleFax.
     */
    public String getTeleFax() {
        return teleFax;
    }

    /**
     * @param teleFax
     *            The teleFax to set.
     */
    public void setTeleFax(String teleFax) {
        this.teleFax = teleFax;
    }

    /**
     * @return Returns the telefono.
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * @param telefono
     *            The telefono to set.
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * @return Returns the telefonoReferente.
     */
    public String getTelefonoReferente() {
        return telefonoReferente;
    }

    /**
     * @param telefonoReferente
     *            The telefonoReferente to set.
     */
    public void setTelefonoReferente(String telefonoReferente) {
        this.telefonoReferente = telefonoReferente;
    }

    /**
     * @return Returns the textNote.
     */
    public String getTextNote() {
        return textNote;
    }

    /**
     * @param textNote
     *            The textNote to set.
     */
    public void setTextNote(String textNote) {
        this.textNote = textNote;
    }
}