/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

/**
 * @persistent
 * @rdbPhysicalName TIPO_EVENTI
 * @rdbPhysicalPrimaryKeyName SYS_C0022033
 */
public class StatoAssegnazioneProtocolloVO {
    private String codice;

    private String descrizione;

    public StatoAssegnazioneProtocolloVO(String codice, String descrizione) {
        this.codice = codice;
        this.descrizione = descrizione;
    }

    /**
     * @return Returns the descrizione.
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * @param descrizione
     *            The descrizione to set.
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * @return Returns the codice.
     */
    public String getCodice() {
        return codice;
    }

    /**
     * @param codice
     *            The codice to set.
     */
    public void setCodice(String codice) {
        this.codice = codice;
    }
}