/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

import it.finsiel.siged.mvc.vo.VersioneVO;

/**
 * @persistent
 * @rdbPhysicalName STRUTTURA_TIPO_DOC
 * @rdbPhysicalPrimaryKeyName SYS_C0022232
 */
public class StrutturaTipoDocVO extends VersioneVO {
    public StrutturaTipoDocVO() {
    }

    /**
     * @rdbPhysicalName STRUTTURA_TIPO_DOC_ID
     * @rdbNotNull
     * @rdbSize 22
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL
     * @rdbPrimaryKey
     */
    private long strutturaTipoDocId;

    /**
     * @rdbPhysicalName DESC_ETICHETTA
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String descrizioneEtichetta;

    /**
     * @rdbPhysicalName STAT_TIPO_CAMPO
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR
     */
    private String statoTipoCampo;

    /**
     * @rdbPhysicalName NUME_LUNGHEZZA
     * @rdbSize 22
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL
     */
    private long lunghezza;

    /**
     * @rdbPhysicalName FLAG_OBBLIGATORIO
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR
     */
    private String flagObbligatorio;

    private TipoDocumentoVO fkTipoDocumento;

    /**
     * @return Returns the descrizioneEtichetta.
     */
    public String getDescrizioneEtichetta() {
        return descrizioneEtichetta;
    }

    /**
     * @param descrizioneEtichetta
     *            The descrizioneEtichetta to set.
     */
    public void setDescrizioneEtichetta(String descrizioneEtichetta) {
        this.descrizioneEtichetta = descrizioneEtichetta;
    }

    /**
     * @return Returns the fkTipoDocumento.
     */
    public TipoDocumentoVO getFkTipoDocumento() {
        return fkTipoDocumento;
    }

    /**
     * @param fkTipoDocumento
     *            The fkTipoDocumento to set.
     */
    public void setFkTipoDocumento(TipoDocumentoVO fkTipoDocumento) {
        this.fkTipoDocumento = fkTipoDocumento;
    }

    /**
     * @return Returns the flagObbligatorio.
     */
    public String getFlagObbligatorio() {
        return flagObbligatorio;
    }

    /**
     * @param flagObbligatorio
     *            The flagObbligatorio to set.
     */
    public void setFlagObbligatorio(String flagObbligatorio) {
        this.flagObbligatorio = flagObbligatorio;
    }

    /**
     * @return Returns the lunghezza.
     */
    public long getLunghezza() {
        return lunghezza;
    }

    /**
     * @param lunghezza
     *            The lunghezza to set.
     */
    public void setLunghezza(long lunghezza) {
        this.lunghezza = lunghezza;
    }

    /**
     * @return Returns the statoTipoCampo.
     */
    public String getStatoTipoCampo() {
        return statoTipoCampo;
    }

    /**
     * @param statoTipoCampo
     *            The statoTipoCampo to set.
     */
    public void setStatoTipoCampo(String statoTipoCampo) {
        this.statoTipoCampo = statoTipoCampo;
    }

    /**
     * @return Returns the strutturaTipoDocId.
     */
    public long getStrutturaTipoDocId() {
        return strutturaTipoDocId;
    }

    /**
     * @param strutturaTipoDocId
     *            The strutturaTipoDocId to set.
     */
    public void setStrutturaTipoDocId(long strutturaTipoDocId) {
        this.strutturaTipoDocId = strutturaTipoDocId;
    }
}