/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

/**
 * @persistent
 * @rdbPhysicalName TIPO_EVENTI
 * @rdbPhysicalPrimaryKeyName SYS_C0022033
 */
public class TipoPersonaVO {
    public TipoPersonaVO(String tipo, String descrizione) {
        this.tipo = tipo;
        this.descrizione = descrizione;
    }

    /**
     * @return Returns the descrizione.
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * @param descrizione
     *            The descrizione to set.
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * @return Returns the tipo.
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * @param tipo
     *            The tipo to set.
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    private String tipo;

    private String descrizione;
}