/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

import it.finsiel.siged.mvc.vo.VersioneVO;

/**
 * @persistent
 * @rdbPhysicalName TIPI_DOCUMENTO
 * @rdbPhysicalPrimaryKeyName SYS_C0022087
 */
public class TipoUfficioVO extends VersioneVO {

    public TipoUfficioVO() {
    }

    public TipoUfficioVO(String codice, String descrizione) {
        this.codice = codice;
        this.descrizione = descrizione;
    }

    private String descrizione;

    private String codice;

    /**
     * @return Returns the codice.
     */
    public String getCodice() {
        return codice;
    }

    /**
     * @param codice
     *            The codice to set.
     */
    public void setCodice(String codice) {
        this.codice = codice;
    }

    /**
     * @return Returns the descrizione.
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * @param descrizione
     *            The descrizione to set.
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }
}