/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

import it.finsiel.siged.mvc.vo.VersioneVO;

import java.util.ArrayList;

/**
 * @persistent
 * @rdbPhysicalName TIPI_DOCUMENTO
 * @rdbPhysicalPrimaryKeyName SYS_C0022087
 */
public class TipoDocumentoVO extends VersioneVO {
    public TipoDocumentoVO() {
    }

    public TipoDocumentoVO(int id, String description) {
        setId(id);
        this.descrizione = description;
    }

    private ArrayList tipiDocumento = new ArrayList();

    private int aooId;

    private String descrizione;

    private String flagAttivazione;

    private int protocolli;

    private int numGGScadenza;

    private String flagDefault;

    public String getDescrizione() {
        return descrizione;
    }

    /**
     * @param descrizioneDoc
     *            The descrizioneDoc to set.
     */
    public void setDescrizioneDoc(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * @return Returns the fkAoo.
     */
    public int getAooId() {
        return aooId;
    }

    /**
     * @param fkAoo
     *            The fkAoo to set.
     */
    public void setAooId(int aooId) {
        this.aooId = aooId;
    }

    /**
     * @return Returns the flagAttivazione.
     */
    public String getFlagAttivazione() {
        return flagAttivazione;
    }

    /**
     * @param flagAttivazione
     *            The flagAttivazione to set.
     */
    public void setFlagAttivazione(String flagAttivazione) {
        this.flagAttivazione = flagAttivazione;
    }

    /**
     * @return Returns the flagDefault.
     */
    public String getFlagDefault() {
        return flagDefault;
    }

    /**
     * @param flagDefault
     *            The flagDefault to set.
     */
    public void setFlagDefault(String flagDefault) {
        this.flagDefault = flagDefault;
    }

    /**
     * @return Returns the protocolli.
     */
    public int getProtocolli() {
        return protocolli;
    }

    /**
     * @param protocolli
     *            The protocolli to set.
     */
    public void setProtocolli(int protocolli) {
        this.protocolli = protocolli;
    }

    /**
     * @param tipiDocumento
     *            The tipiDocumento to set.
     */
    public void setTipiDocumento(ArrayList tipiDocumento) {
        this.tipiDocumento = tipiDocumento;
    }

    /**
     * @return Returns the numGGScadenza.
     */
    public int getNumGGScadenza() {
        return numGGScadenza;
    }

    /**
     * @param numGGScadenza
     *            The numGGScadenza to set.
     */
    public void setNumGGScadenza(int numGGScadenza) {
        this.numGGScadenza = numGGScadenza;
    }

    public TipoDocumentoVO[] getTipiDocumento() {
        TipoDocumentoVO[] tipiDoc = new TipoDocumentoVO[tipiDocumento.size()];
        tipiDocumento.toArray(tipiDoc);
        return tipiDoc;
    }

    public void addTipoDocumento(TipoDocumentoVO tipoDoc) {
        tipiDocumento.add(tipoDoc);
    }

}