/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

/**
 * @persistent
 * @rdbPhysicalName TIPO_EVENTI
 * @rdbPhysicalPrimaryKeyName SYS_C0022033
 */
public class TipoEventoVO {
    public TipoEventoVO() {
    }

    /**
     * @rdbPhysicalName TIPO_EVENTI_ID
     * @rdbNotNull
     * @rdbSize 22
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL
     * @rdbPrimaryKey
     */
    private long tipoEventoId;

    /**
     * @rdbPhysicalName DESC_TIPO_EVENTO
     * @rdbNotNull
     * @rdbSize 200
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String descrizione;

    private Integer funzioneId;

    /**
     * @return Returns the descrizione.
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * @param descrizione
     *            The descrizione to set.
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * @return Returns the funzioneId.
     */
    public Integer getFunzioneId() {
        return funzioneId;
    }

    /**
     * @param funzioneId
     *            The funzioneId to set.
     */
    public void setFunzioneId(Integer funzioneId) {
        this.funzioneId = funzioneId;
    }

    /**
     * @return Returns the tipoEventoId.
     */
    public long getTipoEventoId() {
        return tipoEventoId;
    }

    /**
     * @param tipoEventoId
     *            The tipoEventoId to set.
     */
    public void setTipoEventoId(long tipoEventoId) {
        this.tipoEventoId = tipoEventoId;
    }
}