/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

import it.finsiel.siged.mvc.vo.VersioneVO;

import java.util.ArrayList;

/**
 * @persistent
 * @rdbPhysicalName TIPI_DOCUMENTO
 * @rdbPhysicalPrimaryKeyName SYS_C0022087
 */
public class TipoProcedimentoVO extends VersioneVO {
    public TipoProcedimentoVO() {
    }

    public TipoProcedimentoVO (int idTipo, int idUfficio, String descrizione) {
        setIdTipo(idTipo);
        setIdUfficio(idUfficio);
        this.descrizione = descrizione;
    }

    public TipoProcedimentoVO (int idTipo, String[] idUfficio, String descrizione) {
        setIdTipo(idTipo);
        setIdUffici(idUfficio);
        this.descrizione = descrizione;
    }

    private ArrayList tipiProcedimento = new ArrayList();

    private int aooId;
    
    private int idTipo;
    
    private int idUfficio;
    
    private String[] idUffici;
    
    private String descrizione;

    private String ufficio;
    
    
    
    
    public String getUfficio() {
        return ufficio;
    }

    public void setUfficio(String ufficio) {
        this.ufficio = ufficio;
    }

    public int getAooId() {
        return aooId;
    }

    public void setAooId(int aooId) {
        this.aooId = aooId;
    }

    public int getIdTipo() {
        return idTipo;
    }

    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }

    public int getIdUfficio() {
        return idUfficio;
    }

    public void setIdUfficio(int idUfficio) {
        this.idUfficio = idUfficio;
    }

    public void setTipiProcedimento(ArrayList tipiProcedimento) {
        this.tipiProcedimento = tipiProcedimento;
    }

    public TipoProcedimentoVO[] getTipiProcedimento() {
        TipoProcedimentoVO[] tipiProc = new TipoProcedimentoVO[tipiProcedimento.size()];
        tipiProcedimento.toArray(tipiProc);
        return tipiProc;
    }

    public void addTipoProcedimento(TipoProcedimentoVO tipoProc) {
        tipiProcedimento.add(tipoProc);
    }

    public String getDescrizione() {
        return descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public String[] getIdUffici() {
        return idUffici;
    }

    public void setIdUffici(String[] idUffici) {
        this.idUffici = idUffici;
    }

   
    
    

}