/* Generated by Together */

package it.finsiel.siged.mvc.vo.lookup;

import it.finsiel.siged.mvc.vo.VersioneVO;

public class TitolarioVO extends VersioneVO {
    private String codice;

    private String descrizione;

    private String path;

    private int aooId;

    private int parentId;

    private int massimario;

    private String fullPathDescription;

    public int getAooId() {
        return aooId;
    }

    public void setAooId(int aooId) {
        this.aooId = aooId;
    }

    public String getCodice() {
        return codice;
    }

    public void setCodice(String codice) {
        this.codice = codice;
    }

    public String getDescrizione() {
        return descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public int getParentId() {
        return parentId;
    }

    public void setParentId(int parentId) {
        this.parentId = parentId;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public int getMassimario() {
        return massimario;
    }

    public void setMassimario(int massimario) {
        this.massimario = massimario;
    }

    public String getFullPathDescription() {
        return fullPathDescription;
    }

    public void setFullPathDescription(String fullPathDescription) {
        this.fullPathDescription = fullPathDescription;
    }

}