/* Generated by Together */

package it.finsiel.siged.mvc.vo.protocollo;

import it.finsiel.siged.mvc.vo.BaseVO;

public class AllaccioVO extends BaseVO {
    private int protocolloId;

    private int protocolloAllacciatoId;

    private String allaccioDescrizione;

    private boolean principale;

    public int getProtocolloId() {
        return protocolloId;
    }

    public void setProtocolloId(int allaccioProtocolloId) {
        this.protocolloId = allaccioProtocolloId;
    }

    public String getAllaccioDescrizione() {
        return allaccioDescrizione;
    }

    public void setAllaccioDescrizione(String allaccioView) {
        this.allaccioDescrizione = allaccioView;
    }

    public boolean isPrincipale() {
        return principale;
    }

    public void setPrincipale(boolean principale) {
        this.principale = principale;
    }

    public int getProtocolloAllacciatoId() {
        return protocolloAllacciatoId;
    }

    public void setProtocolloAllacciatoId(int protocolloAllacciatoId) {
        this.protocolloAllacciatoId = protocolloAllacciatoId;
    }
}