/* Generated by Together */

package it.finsiel.siged.mvc.vo.protocollo;

import it.finsiel.siged.mvc.vo.VersioneVO;

import java.sql.Date;

public class AnnotazioneVO extends VersioneVO {

    public AnnotazioneVO() {
    }

    private int fkProtocollo;

    private int codiceAnnotazione;

    private String descrizione;

    private int codiceUserId;

    private Date dataAnnotazione;

    // GET & SET fkProtocollo
    public int getFkProtocollo() {
        return fkProtocollo;
    }

    public void setFkProtocollo(int fkProtocollo) {
        this.fkProtocollo = fkProtocollo;
    }

    // GET & SET descrizione
    public String getDescrizione() {
        return descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * @return Returns the codiceUserId.
     */
    public int getCodiceUserId() {
        return codiceUserId;
    }

    /**
     * @param codiceUserId
     *            The codiceUserId to set.
     */
    public void setCodiceUserId(int codiceUserId) {
        this.codiceUserId = codiceUserId;
    }

    /**
     * @return Returns the dataAnnotazione.
     */
    public Date getDataAnnotazione() {
        return dataAnnotazione;
    }

    /**
     * @param dataAnnotazione
     *            The dataAnnotazione to set.
     */
    public void setDataAnnotazione(Date dataAnnotazione) {
        this.dataAnnotazione = dataAnnotazione;
    }

    /**
     * @return Returns the codiceAnnotazione.
     */
    public int getCodiceAnnotazione() {
        return codiceAnnotazione;
    }

    /**
     * @param codiceAnnotazione
     *            The codiceAnnotazione to set.
     */
    public void setCodiceAnnotazione(int codiceAnnotazione) {
        this.codiceAnnotazione = codiceAnnotazione;
    }
}