/* Generated by Together */

package it.finsiel.siged.mvc.vo.protocollo;

import it.finsiel.siged.mvc.vo.VersioneVO;

import java.util.Date;

public class AssegnatarioVO extends VersioneVO {
    private Date dataAssegnazione;

    private Date dataOperazione;

    private char statoAssegnazione = 'S';

    private boolean competente;

    private int utenteAssegnanteId;

    private int protocolloId;

    private int ufficioAssegnatarioId;

    private int utenteAssegnatarioId;

    private int ufficioAssegnanteId;

    // modifica pino 08/02/2006
    private String msgAssegnatarioCompetente;

    public Date getDataAssegnazione() {
        return dataAssegnazione;
    }

    public void setDataAssegnazione(Date dataAssegnazione) {
        this.dataAssegnazione = dataAssegnazione;
    }

    public Date getDataOperazione() {
        return dataOperazione;
    }

    public void setDataOperazione(Date dataOperazione) {
        this.dataOperazione = dataOperazione;
    }

    public int getUtenteAssegnanteId() {
        return utenteAssegnanteId;
    }

    public void setUtenteAssegnanteId(int utenteAssegnanteId) {
        this.utenteAssegnanteId = utenteAssegnanteId;
    }

    public boolean isCompetente() {
        return competente;
    }

    public void setCompetente(boolean competente) {
        this.competente = competente;
    }

    public int getProtocolloId() {
        return protocolloId;
    }

    public void setProtocolloId(int protocolloId) {
        this.protocolloId = protocolloId;
    }

    public char getStatoAssegnazione() {
        return statoAssegnazione;
    }

    public void setStatoAssegnazione(char statoAssegnazione) {
        this.statoAssegnazione = statoAssegnazione;
    }

    public int getUfficioAssegnanteId() {
        return ufficioAssegnanteId;
    }

    public void setUfficioAssegnanteId(int ufficioAssegnanteId) {
        this.ufficioAssegnanteId = ufficioAssegnanteId;
    }

    public int getUfficioAssegnatarioId() {
        return ufficioAssegnatarioId;
    }

    public void setUfficioAssegnatarioId(int ufficioAssegnatarioId) {
        this.ufficioAssegnatarioId = ufficioAssegnatarioId;
    }

    public int getUtenteAssegnatarioId() {
        return utenteAssegnatarioId;
    }

    public void setUtenteAssegnatarioId(int utenteAssegnatarioId) {
        this.utenteAssegnatarioId = utenteAssegnatarioId;
    }

    public String getMsgAssegnatarioCompetente() {
        return msgAssegnatarioCompetente;
    }

    public void setMsgAssegnatarioCompetente(String msgAssegnatarioCompetente) {
        this.msgAssegnatarioCompetente = msgAssegnatarioCompetente;
    }

}