/* Generated by Together */

package it.finsiel.siged.mvc.vo.protocollo;

import it.finsiel.siged.mvc.vo.VersioneVO;

import java.util.Date;

/**
 * @persistent
 * @rdbPhysicalName PROTOCOLLO_DESTINATARI
 * @rdbPhysicalPrimaryKeyName SYS_C0022262
 */
public class DestinatarioVO extends VersioneVO {
    public DestinatarioVO() {
    }
    String nome;
    String cognome;
    /**
	 * @return the nome
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * @return the cognome
	 */
	public String getCognome() {
		return cognome;
	}

	/**
	 * @param nome the nome to set
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * @param cognome the cognome to set
	 */
	public void setCognome(String cognome) {
		this.cognome = cognome;
	}
	// temp
    private int idx;

    private int mezzoSpedizioneId;

    private Date dataSpedizione;

    private String mezzoDesc;

    // temp
    private String flagTipoDestinatario;

    private String indirizzo;

    private String email;

    private String destinatario;

    private String titoloDestinatario;

    private int titoloId;

    // TODO: aggiunto il 16 feb

    private String codicePostale;

    private String codice;

    private String provinciaId;

    private String intestazione;

    private String citta;

    private boolean flagConoscenza;

    private Date dataEffettivaSpedizione;

    private int protocolloId;

    private String note;

    /**
     * @return Returns the dataEffettivaSpedizione.
     */
    public Date getDataEffettivaSpedizione() {
        return dataEffettivaSpedizione;
    }

    /**
     * @param dataEffettivaSpedizione
     *            The dataEffettivaSpedizione to set.
     */
    public void setDataEffettivaSpedizione(Date dataEffettivaSpedizione) {
        this.dataEffettivaSpedizione = dataEffettivaSpedizione;
    }

    /**
     * @return Returns the dataSpedizione.
     */
    public Date getDataSpedizione() {
        return dataSpedizione;
    }

    /**
     * @param dataSpedizione
     *            The dataSpedizione to set.
     */
    public void setDataSpedizione(Date dataSpedizione) {
        this.dataSpedizione = dataSpedizione;
    }

    public String getIntestazione() {
        return intestazione;
    }

    public void setIntestazione(String intestazione) {
        this.intestazione = intestazione;
    }

    /**
     * @return Returns the destinatario.
     */
    public String getDestinatario() {
        if("F".equals(flagTipoDestinatario) && null != nome && null != cognome){
        	return nome+" "+cognome;
        }else{
        	return destinatario;
        }
    	
    }

    /**
     * @param destinatario
     *            The destinatario to set.
     */
    public void setDestinatario(String destinatario) {
        this.destinatario = destinatario;
    }

    /**
     * @return Returns the email.
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email
     *            The email to set.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    public int getProtocolloId() {
        return protocolloId;
    }

    public void setProtocolloId(int protocolloId) {
        this.protocolloId = protocolloId;
    }

    /**
     * @return Returns the flagConoscenza.
     */
    public boolean getFlagConoscenza() {
        return flagConoscenza;
    }

    /**
     * @param flagConoscenza
     *            The flagConoscenza to set.
     */
    public void setFlagConoscenza(boolean flagConoscenza) {
        this.flagConoscenza = flagConoscenza;
    }

    /**
     * @return Returns the flagTipoDestinatario.
     */
    public String getFlagTipoDestinatario() {
        return flagTipoDestinatario;
    }

    /**
     * @param flagTipoDestinatario
     *            The flagTipoDestinatario to set.
     */
    public void setFlagTipoDestinatario(String flagTipoDestinatario) {
        this.flagTipoDestinatario = flagTipoDestinatario;
    }

    /**
     * @return Returns the indirizzo.
     */
    public String getIndirizzo() {
        return indirizzo;
    }

    /**
     * @param indirizzo
     *            The indirizzo to set.
     */
    public void setIndirizzo(String indirizzo) {
        this.indirizzo = indirizzo;
    }

    public String getCodicePostale() {
        return codicePostale;
    }

    public void setCodicePostale(String codicePostale) {
        this.codicePostale = codicePostale;
    }

    public String getProvinciaId() {
        return provinciaId;
    }

    public void setProvinciaId(String provinciaId) {
        this.provinciaId = provinciaId;
    }

    /**
     * @return Returns the citta.
     */
    public String getCitta() {
        return citta;
    }

    /**
     * @param citta
     *            The citta to set.
     */
    public void setCitta(String citta) {
        this.citta = citta;
    }

    public String getCodice() {
        return codice;
    }

    public void setCodice(String codice) {
        this.codice = codice;
    }

    public int getTitoloId() {
        return titoloId;
    }

    public String getTitoloDestinatario() {
        return titoloDestinatario;
    }

    public void setTitoloDestinatario(String titoloDestinatario) {
        this.titoloDestinatario = titoloDestinatario;
    }

    public void setTitoloId(int titoloId) {
        this.titoloId = titoloId;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public int getMezzoSpedizioneId() {
        return mezzoSpedizioneId;
    }

    public void setMezzoSpedizioneId(int mezzoSpedizioneId) {
        this.mezzoSpedizioneId = mezzoSpedizioneId;
    }

    public String getMezzoDesc() {
        return mezzoDesc;
    }

    public void setMezzoDesc(String mezzoDesc) {
        this.mezzoDesc = mezzoDesc;
    }

    public int getIdx() {
        return idx;
    }

    public void setIdx(int idx) {
        this.idx = idx;
    }

    public void aggiungiMezzospedizione(SpedizioneDestinatarioVO msv) {
        // TODO Verificare con il repository! Metodo vuoto!


    }

}