/* Generated by Together */

package it.finsiel.siged.mvc.vo.protocollo;

import it.finsiel.siged.mvc.vo.VersioneVO;

public class DocumentoVO extends VersioneVO {

    public DocumentoVO() {
    }

    private String descrizione;

    private String contentType;

    private String path;

    private String impronta;

    private int size;

    private String fileName;

    private int idx;

    private boolean mustCreateNew;

    // GET & SET descrizione
    public String getContentType() {
        return contentType;
    }

    public void setContentType(String content) {
        this.contentType = content;
    }

    // GET & SET descrizione
    public String getDescrizione() {
        return descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    // GET & SET path
    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    /**
     * @return Returns the size.
     */
    public int getSize() {
        return size;
    }

    /**
     * @param size
     *            The size to set.
     */
    public void setSize(int size) {
        this.size = size;
    }

    /**
     * @return Returns the impronta.
     */
    public String getImpronta() {
        return impronta;
    }

    /**
     * @param impronta
     *            The impronta to set.
     */
    public void setImpronta(String impronta) {
        this.impronta = impronta;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String name) {
        this.fileName = name;
    }

    public int getIdx() {
        return idx;
    }

    public void setIdx(int idx) {
        this.idx = idx;
    }

    /*
     * se "true" indica che il file va salvato su base dati anche se ha un Id
     * non nullo
     * 
     */
    public boolean isMustCreateNew() {
        return mustCreateNew;
    }

    public void setMustCreateNew(boolean mustCreateNew) {
        this.mustCreateNew = mustCreateNew;
    }
}