/* Generated by Together */

package it.finsiel.siged.mvc.vo.protocollo;

import it.finsiel.siged.model.organizzazione.Organizzazione;
import it.finsiel.siged.model.organizzazione.Ufficio;
import it.finsiel.siged.mvc.bo.TitolarioBO;
import it.finsiel.siged.mvc.vo.VersioneVO;
import it.finsiel.siged.util.DateUtil;
import it.finsiel.siged.util.StringUtil;

import java.util.Date;

/**
 * @persistent
 * @rdbPhysicalName FASCICOLI
 * @rdbPhysicalPrimaryKeyName SYS_C0022208
 */
public class FascicoloVO extends VersioneVO {

    private int aooId;

    private String codice;

    private String descrizione;

    private String nome;

    private long progressivo;

    private int ufficioIntestatarioId;

    private int utenteIntestatarioId;

    private int ufficioResponsabileId;

    private int utenteResponsabileId;

    private String note;

    private int processoId;

    private String oggetto;

    private int registroId;

    private Date dataApertura;

    private Date dataChiusura;
    
    private String dataAperturaStr;

    private String dataChiusuraStr;

    private int stato;

    private int titolarioId;

    // modifiche MinInt 13/02/2006
    private Date dataEvidenza;

    private int annoRiferimento;

    private int tipoFascicolo;

    private int posizioneFascicolo;

    private int condizione;

    private Date dataUltimoMovimento;

    private Date dataCarico;

    private Date dataScarico;

    private Date dataScarto;

    private String propostaScarto;

    // fine modifiche MinInt 13/02/2006
    
    // modifiche 21/03/2006
    
    private String collocazioneLabel1;
    private String collocazioneLabel2;
    private String collocazioneLabel3;
    private String collocazioneLabel4;
    private String collocazioneValore1;
    private String collocazioneValore2;
    private String collocazioneValore3;
    private String collocazioneValore4;
    
    // fine modifiche 21/03/2006

    public int getAooId() {
        return aooId;
    }

    public void setAooId(int aooId) {
        this.aooId = aooId;
    }

    public String getCodice() {
        return codice;
    }

    public void setCodice(String codice) {
        this.codice = codice;
    }


    public Date getDataApertura() {
        return dataApertura;
    }

    public void setDataApertura(Date dataApertura) {
        this.dataApertura = dataApertura;
    }

    public Date getDataChiusura() {
        return dataChiusura;
    }

    public void setDataChiusura(Date dataChiusura) {
        this.dataChiusura = dataChiusura;
    }

    public String getDescrizione() {
        return descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getOggetto() {
        return oggetto;
    }

    public void setOggetto(String oggetto) {
        this.oggetto = oggetto;
    }

    public int getProcessoId() {
        return processoId;
    }

    public void setProcessoId(int processoId) {
        this.processoId = processoId;
    }

    public long getProgressivo() {
        return progressivo;
    }

    public void setProgressivo(long progressivo) {
        this.progressivo = progressivo;
    }

    public int getRegistroId() {
        return registroId;
    }

    public void setRegistroId(int registroId) {
        this.registroId = registroId;
    }

    public int getStato() {
        return stato;
    }

    public void setStato(int stato) {
        this.stato = stato;
    }

    public int getTitolarioId() {
        return titolarioId;
    }

    public void setTitolarioId(int titolarioId) {
        this.titolarioId = titolarioId;
    }

    public int getUfficioIntestatarioId() {
        return ufficioIntestatarioId;
    }

    public void setUfficioIntestatarioId(int ufficioIntestatarioId) {
        this.ufficioIntestatarioId = ufficioIntestatarioId;
    }

    public int getUtenteIntestatarioId() {
        return utenteIntestatarioId;
    }

    public void setUtenteIntestatarioId(int utenteIntestatarioId) {
        this.utenteIntestatarioId = utenteIntestatarioId;
    }

    public int getUfficioResponsabileId() {
        return ufficioResponsabileId;
    }

    public void setUfficioResponsabileId(int ufficioResponsabileId) {
        this.ufficioResponsabileId = ufficioResponsabileId;
    }

    public int getUtenteResponsabileId() {
        return utenteResponsabileId;
    }

    public void setUtenteResponsabileId(int utenteResponsabileId) {
        this.utenteResponsabileId = utenteResponsabileId;
    }

    public int getAnnoRiferimento() {
        return annoRiferimento;
    }

    public void setAnnoRiferimento(int annoRiferimento) {
        this.annoRiferimento = annoRiferimento;
    }

    public Date getDataCarico() {
        return dataCarico;
    }

    public void setDataCarico(Date dataCarico) {
        this.dataCarico = dataCarico;
    }

    public Date getDataScarico() {
        return dataScarico;
    }

    public void setDataScarico(Date dataScarico) {
        this.dataScarico = dataScarico;
    }

    public Date getDataEvidenza() {
        return dataEvidenza;
    }

    public void setDataEvidenza(Date dataEvidenza) {
        this.dataEvidenza = dataEvidenza;
    }

    public Date getDataScarto() {
        return dataScarto;
    }

    public void setDataScarto(Date dataScarto) {
        this.dataScarto = dataScarto;
    }

    public Date getDataUltimoMovimento() {
        return dataUltimoMovimento;
    }

    public void setDataUltimoMovimento(Date dataUltimoMovimento) {
        this.dataUltimoMovimento = dataUltimoMovimento;
    }

    public String getPropostaScarto() {
        return propostaScarto;
    }

    public void setPropostaScarto(String propostaScarto) {
        this.propostaScarto = propostaScarto;
    }

    public int getTipoFascicolo() {
        return tipoFascicolo;
    }

    public void setTipoFascicolo(int tipoFascicolo) {
        this.tipoFascicolo = tipoFascicolo;
    }

    public int getPosizioneFascicolo() {
        return posizioneFascicolo;
    }

    public void setPosizioneFascicolo(int posizioneFascicolo) {
        this.posizioneFascicolo = posizioneFascicolo;
    }

    public int getCondizione() {
        return condizione;
    }

    public void setCondizione(int condizione) {
        this.condizione = condizione;
    }

    public String getPathTitolario() {
        return TitolarioBO.getPathDescrizioneTitolario(getTitolarioId());
    }

    public String getAnnoProgressivo() {
        if (getDataApertura()!=null  && getProgressivo() > 0) {
            return DateUtil.getYear(getDataApertura())
                    + StringUtil.formattaNumeroProtocollo(String
                            .valueOf(progressivo), 6);
        }
        return null;
    }

    public String getDescUfficioIntestatarioId() {
        Ufficio u = Organizzazione.getInstance().getUfficio(
                getUfficioIntestatarioId());
        if (u != null && u.getValueObject() != null)
            return u.getValueObject().getDescription();
        else
            return "";
    }

    public String getCollocazioneLabel1() {
        return collocazioneLabel1;
    }

    public void setCollocazioneLabel1(String collocazioneLabel1) {
        this.collocazioneLabel1 = collocazioneLabel1;
    }

    public String getCollocazioneLabel2() {
        return collocazioneLabel2;
    }

    public void setCollocazioneLabel2(String collocazioneLabel2) {
        this.collocazioneLabel2 = collocazioneLabel2;
    }

    public String getCollocazioneLabel3() {
        return collocazioneLabel3;
    }

    public void setCollocazioneLabel3(String collocazioneLabel3) {
        this.collocazioneLabel3 = collocazioneLabel3;
    }

    public String getCollocazioneLabel4() {
        return collocazioneLabel4;
    }

    public void setCollocazioneLabel4(String collocazioneLabel4) {
        this.collocazioneLabel4 = collocazioneLabel4;
    }

    public String getCollocazioneValore1() {
        return collocazioneValore1;
    }

    public void setCollocazioneValore1(String collocazioneValore1) {
        this.collocazioneValore1 = collocazioneValore1;
    }

    public String getCollocazioneValore2() {
        return collocazioneValore2;
    }

    public void setCollocazioneValore2(String collocazioneValore2) {
        this.collocazioneValore2 = collocazioneValore2;
    }

    public String getCollocazioneValore3() {
        return collocazioneValore3;
    }

    public void setCollocazioneValore3(String collocazioneValore3) {
        this.collocazioneValore3 = collocazioneValore3;
    }

    public String getCollocazioneValore4() {
        return collocazioneValore4;
    }

    public void setCollocazioneValore4(String collocazioneValore4) {
        this.collocazioneValore4 = collocazioneValore4;
    }

    public String getDataChiusuraStr() {
        return dataChiusuraStr;
    }

    public void setDataChiusuraStr(String dataChiusuraStr) {
        this.dataChiusuraStr = dataChiusuraStr;
    }

    public String getDataAperturaStr() {
        return dataAperturaStr;
    }

    public void setDataAperturaStr(String dataAperturaStr) {
        this.dataAperturaStr = dataAperturaStr;
    }
}