/* Generated by Together */

package it.finsiel.siged.mvc.vo.protocollo;

import it.finsiel.siged.mvc.vo.VersioneVO;

public class InvioClassificatiDestinatariVO extends VersioneVO {

    private int documentoId;

    private DestinatarioVO destinatario;

    public DestinatarioVO getDestinatario() {
        return destinatario;
    }

    public void setDestinatario(DestinatarioVO destinatario) {
        this.destinatario = destinatario;
    }

    public int getDocumentoId() {
        return documentoId;
    }

    public void setDocumentoId(int documentoId) {
        this.documentoId = documentoId;
    }
}