/* Generated by Together */

package it.finsiel.siged.mvc.vo.protocollo;

import it.finsiel.siged.mvc.vo.VersioneVO;

public class InvioClassificatiVO extends VersioneVO {

    private int documentoId;

    private int aooId;

    private int ufficioMittenteId;

    private int utenteMittenteId;

    public int getAooId() {
        return aooId;
    }

    public void setAooId(int aooId) {
        this.aooId = aooId;
    }

    public int getDocumentoId() {
        return documentoId;
    }

    public void setDocumentoId(int documentoId) {
        this.documentoId = documentoId;
    }

    public int getUfficioMittenteId() {
        return ufficioMittenteId;
    }

    public void setUfficioMittenteId(int ufficioMittenteId) {
        this.ufficioMittenteId = ufficioMittenteId;
    }

    public int getUtenteMittenteId() {
        return utenteMittenteId;
    }

    public void setUtenteMittenteId(int utenteMittenteId) {
        this.utenteMittenteId = utenteMittenteId;
    }
}