/* Generated by Together */
package it.finsiel.siged.mvc.vo.protocollo;

import it.finsiel.siged.mvc.vo.VersioneVO;
import it.finsiel.siged.mvc.vo.lookup.SoggettoVO;

import java.lang.reflect.Method;
import java.sql.Timestamp;
import java.util.Collection;
import java.util.Date;
import java.util.List;

/**
 * @db: PROTOCOLLI
 */
public class ProtocolloVO extends VersioneVO {
    public final static String FLAG_TIPO_PROTOCOLLO_INGRESSO = "I";

    public final static String FLAG_TIPO_PROTOCOLLO_USCITA = "U";

    public final static String FLAG_TIPO_MITTENTE_PERS_FISICA = "F";

    public final static String FLAG_TIPO_MITTENTE_PERS_GIURIDICA = "G";
    
    public final static String FLAG_TIPO_MITTENTE_MULTI = "M";

    public final static String FLAG_STATO_SCARICO_DEFAULT = "S";

    private String destinatario;

    private String assegnatario;
    
    private String motivazione;

    /**
     * @db: anno_registrazione integer NOT NULL,
     */
    private int annoRegistrazione;

    /**
     * @db: nume_protocollo integer
     */
    private int numProtocollo;

    /**
     * @db: data_registrazione timestamp NOT NULL
     */
    private Date dataRegistrazione;

    /**
     * @db: text_oggetto varchar(2000) NOT NULL
     */
    private String oggetto;

    /**
     * @db: flag_tipo char(1) NOT NULL,
     */
    private String flagTipo;

    /**
     * @db: data_documento timestamp
     */
    private Date dataDocumento;

    /**
     * @db: riservato Boolean NOT NULL DEFAULT false
     */
    private boolean riservato = false;

    /**
     * @db: mozione boolean NOT NULL DEFAULT false
     */
    private boolean mozione;

    /**
     * @db: data_scadenza timestamp
     */
    private Date dataScadenza;

    /**
     * @db: data_effettiva_registrazione timestamp
     */
    private Date dataEffettivaRegistrazione;

    /**
     * @db: data_ricezione timestamp
     */
    private Date dataRicezione;

    /**
     * @db: data_protocollo_mittente timestamp
     */
    private String dataProtocolloMittente;

    /**
     * @db: desc_nome_mittente varchar(40)
     */
    private String nomeMittente;

    /**
     * @db: desc_cognome_mittente varchar(100)
     */
    private String cognomeMittente;

    /**
     * @db: desc_denominazione_mittente varchar(100)
     */
    private String denominazioneMittente;

    /**
     * @db: flag_tipo_mittente char(1) NOT NULL
     */
    private String flagTipoMittente;

    /**
     * @db: nume_protocollo_mittente varchar(20)
     */
    private String numProtocolloMittente;

    /**
     * @db: indi_mittente varchar(100)
     */
    private String mittenteIndirizzo;

    /**
     * @db: indi_cap_mittente varchar(20)
     */
    private String mittenteCap;

    /**
     * @db: indi_localita_mittente varchar(100)
     */
    private String mittenteComune;

    /**
     * @db: indi_provincia_mittente varchar(20)
     */
    private int mittenteProvinciaId;

    /**
     * @db: indi_nazione_mittente varchar(20)
     */
    private String mittenteNazione;
    
    private List<SoggettoVO> mittenti;

    /**
     * @db: data_annullamento timestamp
     */
    private Date dataAnnullamento;

    /**
     * @db: data_scarico timestamp
     */
    private Date dataScarico;

    /**
     * @db: stato_protocollo char(1) NOT NULL DEFAULT 'S'
     */
    private String statoProtocollo;

    /**
     * @db: text_nota_annullamento varchar(2000)
     */
    private String notaAnnullamento;

    /**
     * @db: text_provvedimento_annullament varchar(2000)
     */
    private String provvedimentoAnnullamento;

    /**
     * @db: codi_documento_doc varchar(64)
     */
    private String codDocumentoDoc;

    private Integer documentoPrincipaleId = null;

    /**
     * @db: registro_id integer NOT NULL
     */
    private int registroId;

    /**
     * @db: tipo_documento_id integer NOT NULL
     */
    private int tipoDocumentoId;

    /**
     * @db: titolario_id integer
     */
    private int titolarioId;

    /**
     * @db: ufficio_protocollatore_id integer
     */
    private int ufficioProtocollatoreId;

    /**
     * @db: utente_protocollatore_id integer
     */
    private int utenteProtocollatoreId;

    /**
     * @db: aoo_id integer NOT NULL
     */
    private int aooId;

    /**
     * @db: annotazione_chiave varchar(255)
     */
    private String chiaveAnnotazione;

    /**
     * @db: annotazione_posizione varchar(10)
     */
    private String posizioneAnnotazione;

    private FascicoloVO fascicoloVO;

    private Collection fascicoli;

    /**
     * @db: annotazione_descrizione varchar(2000)
     */
    private String descrizioneAnnotazione;

    private int ufficioMittenteId;

    private int utenteMittenteId;

    private int rispostaId;

    private int numProtocolloEmergenza;

    /**
     * @return Returns the protocolloIdRisposta. contiene l'id del protocollo in
     *         ingresso su cui ? stato creato un protocollo in uscita in
     *         Risposta
     * 
     */
    public int getRispostaId() {
        return rispostaId;
    }

    public void setRispostaId(int rispostaId) {
        this.rispostaId = rispostaId;
    }

    /**
     * @return Returns the ufficioMittenteId.
     */
    public int getUfficioMittenteId() {
        return ufficioMittenteId;
    }

    /**
     * @param ufficioMittenteId
     *            The ufficioMittenteId to set.
     */
    public void setUfficioMittenteId(int ufficioMittenteId) {
        this.ufficioMittenteId = ufficioMittenteId;
    }

    /**
     * @return Returns the utenteMittenteId.
     */
    public int getUtenteMittenteId() {
        return utenteMittenteId;
    }

    /**
     * @param utenteMittenteId
     *            The utenteMittenteId to set.
     */
    public void setUtenteMittenteId(int utenteMittenteId) {
        this.utenteMittenteId = utenteMittenteId;
    }

    public int getAnnoRegistrazione() {
        return annoRegistrazione;
    }

    public void setAnnoRegistrazione(int annoRegistrazione) {
        this.annoRegistrazione = annoRegistrazione;
    }

    public int getAooId() {
        return aooId;
    }

    public void setAooId(int aooId) {
        this.aooId = aooId;
    }

    public String getChiaveAnnotazione() {
        return chiaveAnnotazione;
    }

    public void setChiaveAnnotazione(String chiaveAnnotazione) {
        this.chiaveAnnotazione = chiaveAnnotazione;
    }

    public String getCodDocumentoDoc() {
        return codDocumentoDoc;
    }

    public void setCodDocumentoDoc(String codDocumentoDoc) {
        this.codDocumentoDoc = codDocumentoDoc;
    }

    public String getCognomeMittente() {
        return cognomeMittente;
    }

    public void setCognomeMittente(String cognomeMittente) {
        this.cognomeMittente = cognomeMittente;
    }

    public Date getDataAnnullamento() {
        return dataAnnullamento;
    }

    public void setDataAnnullamento(Date dataAnnullamento) {
        this.dataAnnullamento = dataAnnullamento;
    }

    public Date getDataDocumento() {
        return dataDocumento;
    }

    public void setDataDocumento(Date dataDocumento) {
        this.dataDocumento = dataDocumento;
    }

    public Date getDataEffettivaRegistrazione() {
        return dataEffettivaRegistrazione;
    }

    public void setDataEffettivaRegistrazione(Date dataEffettivaRegistrazione) {
        this.dataEffettivaRegistrazione = dataEffettivaRegistrazione;
    }

    public String getDataProtocolloMittente() {
        return dataProtocolloMittente;
    }

    public void setDataProtocolloMittente(String dataProtocolloMittente) {
        this.dataProtocolloMittente = dataProtocolloMittente;
    }

    public Date getDataRegistrazione() {
        return dataRegistrazione;
    }

    public void setDataRegistrazione(Date dataRegistrazione) {
        this.dataRegistrazione = dataRegistrazione;
    }

    public Date getDataRicezione() {
        return dataRicezione;
    }

    public void setDataRicezione(Date dataRicezione) {
        this.dataRicezione = dataRicezione;
    }

    public Date getDataScadenza() {
        return dataScadenza;
    }

    public void setDataScadenza(Date dataScadenza) {
        this.dataScadenza = dataScadenza;
    }

    public Date getDataScarico() {
        return dataScarico;
    }

    public void setDataScarico(Date dataScarico) {
        this.dataScarico = dataScarico;
    }

    public String getDenominazioneMittente() {
        return denominazioneMittente;
    }

    public void setDenominazioneMittente(String denominazioneMittente) {
        this.denominazioneMittente = denominazioneMittente;
    }

    public String getDescrizioneAnnotazione() {
        return descrizioneAnnotazione;
    }

    public void setDescrizioneAnnotazione(String descrizioneAnnotazione) {
        this.descrizioneAnnotazione = descrizioneAnnotazione;
    }

    public Integer getDocumentoPrincipaleId() {
        return documentoPrincipaleId;
    }

    public void setDocumentoPrincipaleId(int documentoId) {
        if (documentoId == 0) {
            setDocumentoPrincipaleId(null);
        } else {
            setDocumentoPrincipaleId(new Integer(documentoId));
        }
    }

    private void setDocumentoPrincipaleId(Integer documentoPrincipaleId) {
        this.documentoPrincipaleId = documentoPrincipaleId;
    }

    public boolean isMozione() {
        return this.mozione;
    }

    public void setMozione(boolean mozione) {
        this.mozione = mozione;
    }

    public boolean isRiservato() {
        return riservato;
    }

    public void setRiservato(boolean riservato) {
        this.riservato = riservato;
    }

    public String getFlagTipo() {
        return flagTipo;
    }

    public void setFlagTipo(String flagTipo) {
        this.flagTipo = flagTipo;
    }

    public String getFlagTipoMittente() {
        return flagTipoMittente;
    }

    public void setFlagTipoMittente(String flagTipoMittente) {
        this.flagTipoMittente = flagTipoMittente;
    }

    public String getMittenteCap() {
        return mittenteCap;
    }

    public void setMittenteCap(String mittenteCap) {
        this.mittenteCap = mittenteCap;
    }

    public String getMittenteComune() {
        return mittenteComune;
    }

    public void setMittenteComune(String mittenteComune) {
        this.mittenteComune = mittenteComune;
    }

    public String getMittenteIndirizzo() {
        return mittenteIndirizzo;
    }

    public void setMittenteIndirizzo(String mittenteIndirizzo) {
        this.mittenteIndirizzo = mittenteIndirizzo;
    }

    public String getMittenteNazione() {
        return mittenteNazione;
    }

    public void setMittenteNazione(String mittenteNazione) {
        this.mittenteNazione = mittenteNazione;
    }

    public int getMittenteProvinciaId() {
        return mittenteProvinciaId;
    }

    public void setMittenteProvinciaId(int mittenteProvinciaId) {
        this.mittenteProvinciaId = mittenteProvinciaId;
    }

    public String getNomeMittente() {
        return nomeMittente;
    }

    public void setNomeMittente(String nomeMittente) {
        this.nomeMittente = nomeMittente;
    }

    public String getNotaAnnullamento() {
        return notaAnnullamento;
    }

    public void setNotaAnnullamento(String notaAnnullamento) {
        this.notaAnnullamento = notaAnnullamento;
    }

    public int getNumProtocollo() {
        return numProtocollo;
    }

    public void setNumProtocollo(int numProtocollo) {
        this.numProtocollo = numProtocollo;
    }

    public String getNumProtocolloMittente() {
        return numProtocolloMittente;
    }

    public void setNumProtocolloMittente(String numProtocolloMittente) {
        this.numProtocolloMittente = numProtocolloMittente;
    }

    public int getNumProtocolloEmergenza() {
        return numProtocolloEmergenza;
    }

    public void setNumProtocolloEmergenza(int numProtocolloEmergenza) {
        this.numProtocolloEmergenza = numProtocolloEmergenza;
    }

    public String getOggetto() {
        return oggetto;
    }

    public void setOggetto(String oggetto) {
        this.oggetto = oggetto;
    }

    public String getPosizioneAnnotazione() {
        return posizioneAnnotazione;
    }

    public void setPosizioneAnnotazione(String posizioneAnnotazione) {
        this.posizioneAnnotazione = posizioneAnnotazione;
    }

    public String getProvvedimentoAnnullamento() {
        return provvedimentoAnnullamento;
    }

    public void setProvvedimentoAnnullamento(String provvedimentoAnnullamento) {
        this.provvedimentoAnnullamento = provvedimentoAnnullamento;
    }

    public int getRegistroId() {
        return registroId;
    }

    public void setRegistroId(int registroId) {
        this.registroId = registroId;
    }

    public String getStatoProtocollo() {
        if (statoProtocollo == null) {
            return FLAG_STATO_SCARICO_DEFAULT;
        }
        return statoProtocollo;
    }

    public void setStatoProtocollo(String statoTipoScarico) {
        this.statoProtocollo = statoTipoScarico;
    }

    public int getTipoDocumentoId() {
        return tipoDocumentoId;
    }

    public void setTipoDocumentoId(int tipoDocumentoId) {
        this.tipoDocumentoId = tipoDocumentoId;
    }

    public int getTitolarioId() {
        return titolarioId;
    }

    public void setTitolarioId(int titolarioId) {
        this.titolarioId = titolarioId;
    }

    public int getUfficioProtocollatoreId() {
        return ufficioProtocollatoreId;
    }

    public void setUfficioProtocollatoreId(int ufficioProtocollatoreId) {
        this.ufficioProtocollatoreId = ufficioProtocollatoreId;
    }

    public int getUtenteProtocollatoreId() {
        return utenteProtocollatoreId;
    }

    public void setUtenteProtocollatoreId(int utenteProtocollatoreId) {
        this.utenteProtocollatoreId = utenteProtocollatoreId;
    }

    public String toString() {
        Class c = ProtocolloVO.class;
        Method[] met = c.getMethods();
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < met.length; i++) {
            try {
                if (met[i].getName().startsWith("get"))
                    sb.append(met[i].getName() + " : "
                            + met[i].invoke(this, null) + "\n");
            } catch (Exception e) {

            }
        }
        return sb.toString();
    }

    public FascicoloVO getFascicoloVO() {
        return fascicoloVO;
    }

    public void setFascicoloVO(FascicoloVO fascicoloVO) {
        this.fascicoloVO = fascicoloVO;
    }

    public Collection getFascicoli() {
        return fascicoli;
    }

    public void setFascicoli(Collection fascicoli) {
        this.fascicoli = fascicoli;
    }

    public String getDestinatario() {
        return destinatario;
    }

    public void setDestinatario(String destinatario) {
        this.destinatario = destinatario;
    }

    public String getAssegnatario() {
        return assegnatario;
    }

    public void setAssegnatario(String assegnatario) {
        this.assegnatario = assegnatario;
    }

    public long getKey() {
        return getKey(getRegistroId(), getAnnoRegistrazione(),
                getNumProtocollo());
    }

    public static long getKey(int registro, int anno, int numero) {
        // return registro * 1000000000000l + anno * 100000000l + numero;
        return registro * 100000000000l + anno * 10000000l + numero;
    }

    
    //Modifica Daniele Sanna  03/09/2008
	public void setMittenti(List<SoggettoVO> mittenti) {
		this.mittenti = mittenti;
	}
	
	public List<SoggettoVO> getMittenti(){
		return this.mittenti;
	}

	public String getMotivazione() {
		return motivazione;
	}

	public void setMotivazione(String motivazione) {
		this.motivazione = motivazione;
	}

}