/* Generated by Together */

package it.finsiel.siged.mvc.vo;

/**
 * @db: registro
 */
public class ImpiegatoVO {

    // Attributi

    private String matricola;

    private String cognome;

    private String nome;

    private String dataNascita;

    private String comune;

    private String provincia;

    private String qualifica;
    
    private String nomeCompleto;

    // Costruttori

    public String getNomeCompleto() {
        return nomeCompleto;
    }

    public void setNomeCompleto(String nomeCompleto) {
        this.nomeCompleto = nomeCompleto;
    }

    public ImpiegatoVO() {
        // costruttore vuoto
    }

    public ImpiegatoVO(String matricola, String cognome, String nome,
            String dataNascita, String comune, String provincia,
            String qualifica) {
        setMatricola(matricola);
        setCognome(cognome);
        setNome(nome);
        setDataNascita(dataNascita);
        setComune(comune);
        setProvincia(provincia);
        setQualifica(qualifica);
        setNomeCompleto(cognome+" "+nome);
    }

    // Set&Get
    public String getCognome() {
        return cognome;
    }

    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    public String getComune() {
        return comune;
    }

    public void setComune(String comune) {
        this.comune = comune;
    }

    public String getDataNascita() {
        return dataNascita;
    }

    public void setDataNascita(String dataNascita) {
        this.dataNascita = dataNascita;
    }

    public String getMatricola() {
        return matricola;
    }

    public void setMatricola(String matricola) {
        this.matricola = matricola;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getProvincia() {
        return provincia;
    }

    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    public String getQualifica() {
        return qualifica;
    }

    public void setQualifica(String qualifica) {
        this.qualifica = qualifica;
    }

    public String toString() {
        StringBuffer retBuff = new StringBuffer();
        retBuff.append("Matricola=").append(matricola).append(",");
        retBuff.append("Cognome=").append(cognome).append(",");
        retBuff.append("Nome=").append(nome);
        retBuff.append("Provincia=").append(provincia);
        retBuff.append("Comune=").append(comune);
        retBuff.append("Qualifica=").append(qualifica);
        return retBuff.toString();
    }

}