/* Generated by Together */

package it.finsiel.siged.mvc.vo;



/**
 * @db: registro
 */
public class MigrazioneVO {
    private int Numero;
    private int Anno;
    public int getAnno() {
        return Anno;
    }
    public void setAnno(int anno) {
        Anno = anno;
    }
    public int getNumero() {
        return Numero;
    }
    public void setNumero(int numero) {
        Numero = numero;
    }
    
    
    }