/* Generated by Together */

package it.finsiel.siged.mvc.vo.log;

import java.util.Date;

public class EventoVO {
    public EventoVO() {
    }

    public Date getData() {
        return data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    public String getDestinatari() {
        return destinatari;
    }

    public void setDestinatari(String destinatari) {
        this.destinatari = destinatari;
    }

    public String getErrore() {
        return errore;
    }

    public void setErrore(String errore) {
        this.errore = errore;
    }

    public int getEventoId() {
        return eventoId;
    }

    public void setEventoId(int eventoId) {
        this.eventoId = eventoId;
    }

    public String getOggetto() {
        return oggetto;
    }

    public void setOggetto(String oggetto) {
        this.oggetto = oggetto;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public int getTipoLog() {
        return tipoLog;
    }

    public void setTipoLog(int tipoLog) {
        this.tipoLog = tipoLog;
    }

    private int eventoId;

    private Date data;

    private String oggetto;

    private String tipo;

    private String errore;

    private String destinatari;

    private int tipoLog;

}