/* Generated by Together */

package it.finsiel.siged.mvc.vo.log;

import java.util.Date;

public class LogAcquisizioneMassivaVO {
    public LogAcquisizioneMassivaVO() {
    }

    private int aooId;

    private Date data;

    private String fileName;

    private String errore;

    public int getAooId() {
        return aooId;
    }

    public void setAooId(int aooId) {
        this.aooId = aooId;
    }

    public Date getData() {
        return data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    public String getErrore() {
        return errore;
    }

    public void setErrore(String errore) {
        this.errore = errore;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
}