/* Generated by Together */

package it.finsiel.siged.mvc.vo.posta;

/**
 * @persistent
 * @rdbPhysicalName ALLEGATI_MESSAGGI
 * @rdbPhysicalPrimaryKeyName SYS_C0022148
 */
public class AllegatoMessaggioVO {
    public AllegatoMessaggioVO() {
    }

    /**
     * @return Returns the allegatoMessaggiId.
     */
    public long getAllegatoMessaggiId() {
        return allegatoMessaggiId;
    }

    /**
     * @param allegatoMessaggiId
     *            The allegatoMessaggiId to set.
     */
    public void setAllegatoMessaggiId(long allegatoMessaggiId) {
        this.allegatoMessaggiId = allegatoMessaggiId;
    }

    /**
     * @return Returns the blobAllegatoPosta.
     */
    public Object getBlobAllegatoPosta() {
        return blobAllegatoPosta;
    }

    /**
     * @param blobAllegatoPosta
     *            The blobAllegatoPosta to set.
     */
    public void setBlobAllegatoPosta(Object blobAllegatoPosta) {
        this.blobAllegatoPosta = blobAllegatoPosta;
    }

    /**
     * @return Returns the descrizioneAllegatoFileName.
     */
    public String getDescrizioneAllegatoFileName() {
        return descrizioneAllegatoFileName;
    }

    /**
     * @param descrizioneAllegatoFileName
     *            The descrizioneAllegatoFileName to set.
     */
    public void setDescrizioneAllegatoFileName(
            String descrizioneAllegatoFileName) {
        this.descrizioneAllegatoFileName = descrizioneAllegatoFileName;
    }

    /**
     * @return Returns the messaggioPosta.
     */
    public EmailVO getMessaggioPosta() {
        return messaggioPosta;
    }

    /**
     * @param messaggioPosta
     *            The messaggioPosta to set.
     */
    public void setMessaggioPosta(EmailVO messaggioPosta) {
        this.messaggioPosta = messaggioPosta;
    }

    /**
     * @return Returns the statoTipoAllegato.
     */
    public String getStatoTipoAllegato() {
        return statoTipoAllegato;
    }

    /**
     * @param statoTipoAllegato
     *            The statoTipoAllegato to set.
     */
    public void setStatoTipoAllegato(String statoTipoAllegato) {
        this.statoTipoAllegato = statoTipoAllegato;
    }

    /**
     * @rdbPhysicalName ALLEGATI_MESSAGGI_ID
     * @rdbNotNull
     * @rdbSize 22
     * @rdbDigits 0
     * @rdbLogicalType DECIMAL
     * @rdbPrimaryKey
     */
    private long allegatoMessaggiId;

    /**
     * @rdbPhysicalName BLOB_ALLEGATO_POSTA
     * @rdbLogicalType OTHER
     */
    private Object blobAllegatoPosta;

    /**
     * @rdbPhysicalName DESC_ALLEGATO_FILE_NAME
     * @rdbNotNull
     * @rdbSize 254
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     */
    private String descrizioneAllegatoFileName;

    /**
     * @rdbPhysicalName STAT_TIPO_ALLEGATO
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR
     */
    private String statoTipoAllegato;

    /** @rdbPhysicalName SYS_C0022149 */
    private EmailVO messaggioPosta;
}