/* Generated by Together */

package it.finsiel.siged.mvc.vo.posta;

import it.finsiel.siged.mvc.vo.VersioneVO;

import java.util.Date;

public class EmailVO extends VersioneVO {
    public EmailVO() {
    }

    private String oggetto;

    private String testoMessaggio;

    private String nomeMittente;

    private String emailMittente;

    private String flagTipo;

    private Date dataRicezione;

    private Date dataSpedizione;

    private int flagEliminato;

    private String segnatura;

    private String contentType;

    private int aooId;

    public Date getDataSpedizione() {
        return dataSpedizione;
    }

    public void setDataSpedizione(Date dataInvio) {
        this.dataSpedizione = dataInvio;
    }

    /**
     * @return Returns the dataRicezione.
     */
    public Date getDataRicezione() {
        return dataRicezione;
    }

    /**
     * @param dataRicezione
     *            The dataRicezione to set.
     */
    public void setDataRicezione(Date dataRicezione) {
        this.dataRicezione = dataRicezione;
    }

    /**
     * @return Returns the flagEliminato.
     */
    public int getFlagEliminato() {
        return flagEliminato;
    }

    /**
     * @param flagEliminato
     *            The flagEliminato to set.
     */
    public void setFlagEliminato(int flagEliminato) {
        this.flagEliminato = flagEliminato;
    }

    /**
     * @return Returns the flagTipo.
     */
    public String getFlagTipo() {
        return flagTipo;
    }

    /**
     * @param flagTipo
     *            The flagTipo to set.
     */
    public void setFlagTipo(String flagTipo) {
        this.flagTipo = flagTipo;
    }

    /**
     * @return Returns the textContent.
     */
    public String getTestoMessaggio() {
        return testoMessaggio;
    }

    /**
     * @param textContent
     *            The textContent to set.
     */
    public void setTestoMessaggio(String textContent) {
        this.testoMessaggio = textContent;
    }

    /**
     * @return Returns the Oggetto.
     */
    public String getOggetto() {
        return oggetto;
    }

    /**
     * @param textSubject
     *            The Oggetto to set.
     */
    public void setOggetto(String textSubject) {
        this.oggetto = textSubject;
    }

    /**
     * @return Returns the segnatura.
     */
    public String getSegnatura() {
        return segnatura;
    }

    /**
     * @param segnatura
     *            The segnatura to set.
     */
    public void setSegnatura(String segnatura) {
        this.segnatura = segnatura;
    }

    /**
     * @return Returns the contentType.
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * @param contentType
     *            The contentType to set.
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * @return Returns the emailMittente.
     */
    public String getEmailMittente() {
        return emailMittente;
    }

    /**
     * @param emailMittente
     *            The emailMittente to set.
     */
    public void setEmailMittente(String emailMittente) {
        this.emailMittente = emailMittente;
    }

    /**
     * @return Returns the nomeMittente.
     */
    public String getNomeMittente() {
        return nomeMittente;
    }

    /**
     * @param nomeMittente
     *            The nomeMittente to set.
     */
    public void setNomeMittente(String nomeMittente) {
        this.nomeMittente = nomeMittente;
    }

    public int getAooId() {
        return aooId;
    }

    public void setAooId(int aooId) {
        this.aooId = aooId;
    }
}