/* Generated by Together */

package it.finsiel.siged.mvc.vo.documentale;

import it.finsiel.siged.mvc.vo.protocollo.AssegnatarioVO;

public class AssegnatarioDocumentoVO extends AssegnatarioVO {

    private int documentoId;

    private String permesso;

    public int getDocumentoId() {
        return documentoId;
    }

    public void setDocumentoId(int documentoId) {
        this.documentoId = documentoId;
    }

    public String getPermesso() {
        return permesso;
    }

    public void setPermesso(String permesso) {
        this.permesso = permesso;
    }
}